### ISSUE TITLE
LENGTH ERROR in Link.Create when flatten option is set

### ISSUE THREAD

**Issue by ndrogers** [Dyalog/link#100]
When linking without flatten, there are no issues. 

When linking with flatten option set, using both methods: 
 ]link.create # '/users/<username>/git/myfolder' -flatten
* Command Execution Failed: LENGTH ERROR
      
n.(flatten dir←1 '/users/<username>/git/myfolder')
      n ⎕SE.Link.Create # n.dir
LENGTH ERROR: Right argument must be a vector of correct length
      n ⎕SE.Link.Create # n.dir

**Comment by abrudz** [comment]
I cannot reproduce this with c293d59d358cd381b7befb15720d122cb400cd14 — @ndrogers can you?

**Comment by nicolas-dyalog** [comment]
Cannot reproduce in LInk v2.1
