### ISSUE TITLE
Add property to Link that returns version information

### ISSUE THREAD

**Issue by stampes** [Dyalog/link#103]
In order not to maintain your own versioning scheme would it be nice if you always could ask the Link code for its 'version' - this can be a GitSha or a date or something else that uniquely defines the release of the product

**Comment by stampes** [comment]
What about using the Release functionality - could that solve part of this?

**Comment by e9gille** [comment]
Link should be treated as any project and carry a version number. It would also make sense to build a distribution version as @stampes suggests. If you clone a repository you probably already know how to figure out what you are working with by checking the current branch or check the log. 

The sha on its own is not as friendly as a semantic version number. If you are working on the bleeding edge (a non-tagged commit) and want to report an issue, then it would be useful, but as i said, if you do you probably know how to get it :)

**Comment by nicolas-dyalog** [comment]
Fixed in Link v2.1 which has a ⎕SE.Link.Version function
