### ISSUE TITLE
⎕SE.Link.Add fails to create file 

### ISSUE THREAD

**Issue by ndrogers** [Dyalog/link#104]
When calling ⎕SE.Link.Add 'newfile', Add fails to create a file in the directory when link.watch≡'dir'

Fix appears to be called where source ≡ '' every time, how will Fix ever work then?
Line 19 in ⎕SE.Link.Add 'file'
```

:For item :In items
         :If ×≢⎕NC item
             (ns name)←item⊆⍨⌽≤\⌽item≠'.'
             ns name Fix''
```

Line 42 in Fix
```
:If 'none' 'dir'∊⍨⊂link.watch ⍝ Not watching the workspace
    :If 0=≢src
         →0 ⍝ Just notification, probably editor callback. No more to do.     
```

**Comment by abrudz** [comment]
It seems to work for me in c293d59d358cd381b7befb15720d122cb400cd14 — can you still reproduce it?

`ns name Fix''` is fine as `Fix` will look up the source of `name` in `ns`:
```apl
     nosrc←0=≢src
```
…
```apl
         :If nosrc                       ⍝ Source not provided - find it
             :Select ⌊nc
             :Case 2
                 src←ns⍎name
             :CaseList 3 4
                 src←ns.⎕NR name
             :Case 9
                 src←⎕SRC ns⍎name
```

**Comment by nicolas-dyalog** [comment]
If you're asking for adding a filename, then you don't need to call Add, you simply need to create the file in the directory.
Link.Add is meant to be used on APL variable names, which are not exported to disk by default.
This does work in Link v2.1 
https://github.com/Dyalog/link/blob/master/help/Link.Add.md
