### ISSUE TITLE
Reverting apl functions in git repository deletes the function from workspace 

### ISSUE THREAD

**Issue by cenghoff** [Dyalog/link#106]
I have a setup, where a "git" repository is linked to the workspace.

When a function is modified in the session, the file is changed accordingly. Afterwards I want to discard the change via a "git restore"  or "git checkout" 

The Dyalog Link does not seem to handle this correct. Instead of modifying the function in workspace, the the function is deleted from workspace.

To reproduce, where vcsBranchList is modified and reverted:

In APL session:

            dir←'c:\repos\libwork\src'
            ⎕se.Link.Create # dir
      Linked: # ←→ c:\repos\libwork\src
      ↑ 5177⌶⍬
      vcsBranchList      #  3  c:/repos/libwork/src/vcsBranchList.aplf      0 0  1e4a159f  2019 10 22 10 43 16 206 
      opsQcExec_GetSpec  #  3  c:/repos/libwork/src/opsQcExec_GetSpec.aplf  0 0  5da40aa1  2019 10 22 8 10 45 681  
      opsQcExec_Chk238   #  3  c:/repos/libwork/src/opsQcExec_Chk238.aplf   0 0  c833060d  2019 10 22 8 10 45 680  

       )ed vcsBranchList
       ↑ 5177⌶⍬
      vcsBranchList      #  3  c:/repos/libwork/src/vcsBranchList.aplf      0 0  53a8f679  2019 10 22 11 15 0 744 
      opsQcExec_GetSpec  #  3  c:/repos/libwork/src/opsQcExec_GetSpec.aplf  0 0  5da40aa1  2019 10 22 8 10 45 681 
      opsQcExec_Chk238   #  3  c:/repos/libwork/src/opsQcExec_Chk238.aplf   0 0  c833060d  2019 10 22 8 10 45 680 

In git command line:

      git restore .\src\vcsBranchList.aplf

In APL session:

       ↑ 5177⌶⍬            
      opsQcExec_GetSpec  #  3  c:/repos/libwork/src/opsQcExec_GetSpec.aplf  0 0  5da40aa1  2019 10 22 8 10 45 681 
      opsQcExec_Chk238   #  3  c:/repos/libwork/src/opsQcExec_Chk238.aplf   0 0  c833060d  2019 10 22 8 10 45 680 

      ⎕nc'vcsBranchList'
     0

Is there any Link property,  which needs to be specified to handle this situation?

**Comment by abrudz** [comment]
I can't seem to reproduce this in c293d59d358cd381b7befb15720d122cb400cd14 — can you reproduce it in that version?

**Comment by stampes** [comment]
I have just reproduced this with the most recent apl (version 17.1.37304) and the pinned version of Link target for 17.1. I have uploaded the test repository used by Conny to you ftp site in subfolder "Issue 106 Link"

**Comment by abrudz** [comment]
Both Vince and I have failed to reproduce this using your uploaded repo on the given versions of Dyalog and Link. Maybe there is a timing issue at play here.

**Comment by nicolas-dyalog** [comment]
can't reproduce in link v2.1 either
this might have been due to "git restore" being a buggy experimental command for some time
