### ISSUE TITLE
]break -all gives VALUE ERROR on Linux

### ISSUE THREAD

**Issue by rikedyp** [Dyalog/link#111]
IDE:
  Version: 4.2.3437
  Platform: Win32
  Date: 2019-08-13 14:55:17 +0200
  Git commit: 691f47856e05a36f70847313b23e061a0cf95392
  Preferences:{
    "autocompletion":"shell",
    "ime":"0",
    "kbdLocale":"en_GB",
    "keys":"{\"FX\":[\"Ctrl-S\"]}",
    "selectedExe":"C:\\Program Files\\Dyalog\\Dyalog APL-64 17.1 Unicode\\dyalog.exe",
    "zoom":"5"
  }

Interpreter:
  Version: 17.1.36845
  Platform: Linux-64
  Edition: Unicode/64
  Date: Aug 15 2019 at 00:13:45
Ubuntu 18.04

**Comment by nicolas-dyalog** [comment]
]Link.break -all has never been documented to work.

In link v2.1, ]link.break # correctly unlinks all children of #, thereby unlinking all workspace links.

**Comment by abrudz** [comment]
There can be links other places than in #
]link.break -all should in fact break all existing links.

**Comment by nicolas-dyalog** [comment]
right. Fixed in v2.1
