### ISSUE TITLE
]link.break ns can give a SYNTAX ERROR if you try to break a link to an empty directory

### ISSUE THREAD

**Issue by dyavc** [Dyalog/link#112]
17.1 unicode 64-bit, ]uversion link.break is version:    2.12                                                                    commit:     2019 10 18 Adam: Fix ]Add help                                           

)ns mytest
#.mytest
       ]link.Create mytest d:\git\EmptyDir

Linked: #.mytest ←→ d:\git\EmptyDir
      ]link.break mytest
* Command Execution Failed: SYNTAX ERROR

**Comment by dyavc** [comment]
it does seem to work later if I create another link with another namespace to a directory that does contain some files 

]link.Create mytest2 d:\git\Test2
Linked: #.mytest2 ←→ d:\git\test2

      ]link.break mytest
Unlinked 0 items: #.mytest

**Comment by nicolas-dyalog** [comment]
Fixed in link v2.1
