### ISSUE TITLE
Link.Refresh does not accept namespace left argument

### ISSUE THREAD

**Issue by bpbecker** [Dyalog/link#115]
According to the API documentation, a namespace containing option settings can be passed as an optional left argument to the API functions.  Link.Refresh does not accept a left argument.

**Comment by nicolas-dyalog** [comment]
This piece of documenation is wrong. ⎕SE.Link.Fix doesn't take a namespace as left argument.

**Comment by nicolas-dyalog** [comment]
Documentation fixed in Link v2.1
