### ISSUE TITLE
Review ⎕SE.Link.Create strategy

### ISSUE THREAD

**Issue by nicolas-dyalog** [Dyalog/link#136]
At the moment, link.create requires the source to exist (the directory
by default).

Q1 - Could we make it slightly more clever, and in the case where the
namespace exists but not the directory, then default to source=ns ? Of
course if source=dir was *explicitly* set by the user then it would
still fail.

Q2 - Could we go one step further and allow BOTH the namespace and the
directory not to exist ? Again, that would work ONLY if source was not
explicitly set, and setting source explicitly (to dir or ns) would make
it fail.

Q3 - The default setting for source could then be renamed "auto" which
means : use which ever is not empty as the source. If both are
non-empty, it would fail. If both don't exist, it would create both.

Q4 - Can we remove the source=both setting ? I can't think of a useful
realistic case. It just opens the door to losing code. And it's badly
named because what it really does at the moment is to overwrite files
with APL.

Q5 - should create fail when the non-source is non-empty. At the moment it completely ignores the non-source side, leaving the link in a conflict state if the non-source has differing code. Pretty bad.

**Comment by mbaas2** [comment]
Q2: +1 from me! ;)

**Comment by nicolas-dyalog** [comment]
Q6 - shouldn't current space be the default namespace to link.create ?

**Comment by dyavc** [comment]
Q1: +1  a customer says (28 july 20)  that directory should be created by default if it does not exist and our docs seem to say that 
      ]link.create -???
──────────────────────────────────────────────────────────────────────────                                    
                                                                                                                   
]LINK.Create                                                                                                       
                                                                                                                   
Link a namespace with a directory (create one or both if absent)

**Comment by nicolas-dyalog** [comment]
design decision : 
- Q1, Q3, Q4, Q5 are OK
- Q2 is not OK
- Q6 is OK for UCMD, not for ⎕SE.Link

**Comment by nicolas-dyalog** [comment]
Fixed in link v2.1
