### ISSUE TITLE
Length error on create

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/link#141]
**Describe the bug**
 I just wanted to do a silly test and almost expected it to fail - but it should have failed differently ;)

**To Reproduce**
Steps to reproduce the behaviour: (may depend on the content of your \temp-folder)
````
       ]link.create #.foo \temp
* Command Execution Failed: LENGTH ERROR
        ]udebug on
Was OFF
      ]link.create #.foo \temp
LENGTH ERROR
Run[25] ⎕SE.SALTUtils.c.Link.(RSLT←OPTS(⎕SE.Link⍎CMD)ARGS) ⍝ dot our way home
                                       ∧

````

**Expected behaviour**
There do exist some .aplf-Files in various subfolders - but of course the overwhelming majority of files there has nothing todo with APL. I think the best result in that case would be a ns-structure that reflected what I had below /temp and the fns defined where possible.
The current `LENGTH ERROR` gives me no indication whether I did something wrong or if there was an internal problem.

**Desktop (please complete the following information):**
 - OS: Win10
 - APL version: 180u64-34872
 - `⎕SE.Link.Version`: 2.0.2

**Comment by nicolas-dyalog** [comment]
Cannot reproduce in lin v2.0.3.
