### ISSUE TITLE
]Link.List: Column "Items" content does not match doc

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/link#142]
**Describe the bug**
According to the [wiki](https://github.com/Dyalog/link/wiki/Link.List), ]link.list reports the "number of linked items scripts" in the Items column,
But what it actually shows looks more like the number of "linked items" (with classes and fns inside classes being counted separately)

**To Reproduce**
Steps to reproduce the behaviour:
````
      )ns #.foo
#.foo
      ⎕mkdir'c:\temp\foo'
      ]link.create #.foo c:\temp\foo
Linked: #.foo ←→ c:\temp\foo
      )ed ○foo.goo
````
paste the following
````
:Class goo
    ∇ hoo
    ∇
:EndClass
````
and exit.
```
      ]link.list
┌─────────┬───────────┬─────┐
│Namespace│Directory  │Items│
├─────────┼───────────┼─────┤
│#.foo    │c:/temp/foo│2    │
└─────────┴───────────┴─────┘
      ⊃0 (⎕NINFO⍠1) 'c:/temp/foo/*.*'
┌────────────────────┐
│c:/temp/foo/goo.aplc│
└────────────────────┘
````

**Expected behaviour**
Maybe it's just the wording in the wiki that needs to be updated - "linked scripted items" instead of "linked items scripts"? Or it it supposed to actually count "linked items scripts", it should return 1 in the example.

**Desktop (please complete the following information):**
 - OS: 10.1
 - APL 180u64-38472
 - `⎕SE.Link.Version`:2.0.2

**Comment by nicolas-dyalog** [comment]
Fixed in Link v2.1
