### ISSUE TITLE
Source lost if NS or Class are edited in APL and have errors making them unfixable

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/link#143]
**Describe the bug**
If the APL editor is used to edit a namespace or class in such a way that it cannot be fixed due to errors, the APL editor allows you to "fix anyway", but Link subsequently deletes the object and the source code is lost.

**To Reproduce**
)ed a linked namespace. Change :EndNamespace to :EndClass.

**Expected behaviour**
Nothing - the source should be preserved as typed.

**Desktop (please complete the following information):**
 - `⎕SE.Link.Version`: 2.0.2

**Comment by nicolas-dyalog** [comment]
Does not reproduce in link v2.1

**Comment by nicolas-dyalog** [comment]
Does not reproduce in link v2.1
