### ISSUE TITLE
Link can produce unloadable files

### ISSUE THREAD

**Issue by nicolas-dyalog** [Dyalog/link#144]
**Describe the bug**
Link can produce unloadable files when fixing invalid code (e.g. a trailing ';' at the end of line[0] of a tradfn)

**To Reproduce**
Steps to reproduce the behaviour:
1. ⎕MKDIR '/tmp/linkbug'
2. ]link.create # /tmp/linkbug
3. )ed ⍟ns
4. paste the following code
:Namespace ns
    ∇ res←foo arg
      res←arg
    ∇
:EndNamespace
5. fix and exit editor
6. )ed ns  ⍝ again
7. add a trailing ';' at the end of ns.foo[0]
:Namespace ns
    ∇ res←foo arg;
      res←arg
    ∇
:EndNamespace
8. fix (editor will warn you that fix failed) then discard changes to exit
9. ]link.break #
10.]link.create # /tmp/linkbug

**Expected behaviour**
We need to decide whether this is normal behaviour or not. The alternative is that Link does NOT update the file when the fix failed.

**Comment by mkromberg** [comment]
I think the behaviour is desirable - we should possibly warn the user that the file will need to be edited with an external editor before it can be loaded again. The alternative - NOT allowing saving the current file - is how the interpreter used to behave. It would not let you out of the editor if you could not fix the object without errors. This was an absolute PITA and I was very happy when the interpreter was enhanced to allow you to save a "broken" class or namespace.

**Comment by nicolas-dyalog** [comment]
Three more thoughts to the discussion:
- if we save the "broken" code, then we must be able to load it back
- if the user choses to discard the "broken" code, then the broken changes must be discarded from file too (at the moment we leave them there).
- every deviation from the paradigm "workspace in sync with files at all times" will make the user's life slightly worse.

**Comment by mkromberg** [comment]
In the future, a lot of editing will happen using 3rd party editors, and source files will regularly not be loadable into APL due to errors. Link needs to view this situation as "normal", because it is unavoidable. Forcing the user to discard his work in progress will not improve his or her life.

**Comment by nicolas-dyalog** [comment]
Requires fix to mantis 18485

**Comment by nicolas-dyalog** [comment]
Fixed in Link v2.1 / Dyalog v19.0
