### ISSUE TITLE
allow trailing slash in directory

### ISSUE THREAD

**Issue by nicolas-dyalog** [Dyalog/link#146]
**Describe the bug**
Link.Create doesn't allow a trailing slash (or backslash) in directory name.

**To Reproduce**
1. ⎕MKDIR '/tmp/linkbug/'
2. ]link.create # /tmp/linkbug/

**Expected behaviour**
Should link to /tmp/linkbug. Instead it errors with "Source directory not found"

**Comment by abrudz** [comment]
I disagree.

]link.create something /tmp/linkbug/ should use /tmp/linkbug/something

**Comment by nicolas-dyalog** [comment]
> I disagree.
> 
> `]link.create something /tmp/linkbug/` should use `/tmp/linkbug/something`

Good point. That's more powerful, but also more confusing (one more rule to remember when using it). Many people (including myself) expect '/dir/' and '/dir' to mean the same thing when talking about a directory.

Anyhow it's not a bug, it's a design discussion.

**Comment by nicolas-dyalog** [comment]
trailing slash is now reserved for future extension
