### ISSUE TITLE
Have GUI wizard for empty and/or incorrect commands

### ISSUE THREAD

**Issue by nicolas-dyalog** [Dyalog/link#147]
when ]link.create fails or is empty, it should pop up some GUI to help the user specify which namespace should be linked to which directory, along with widgets for the various options.

**Comment by nicolas-dyalog** [comment]
Will not be fixed.
I'd rather close this now than leave it open for the rest of my life.

**Comment by abrudz** [comment]
It should be fairly easy for a 3rd party to write a GUI cover for Link.
