### ISSUE TITLE
RIDE: linked function removes monitor/trace points in it

### ISSUE THREAD

**Issue by vlnn** [Dyalog/link#148]
**Describe the bug**
Fixing linked function deletes all break/monitor/trace points (this is not the case in normal, unlinked functions, thus creating inconsistency).

**To Reproduce**
Steps to reproduce the behaviour:
1. Link some functions in session
2. Open the function in editor
3. Add some break/trace/monitor points using mouse
4. Make some changes
4.1 Potentially repeat 3 and 4
5. Press Esc and choose "Fix as code in workspace"
6. Open function in the editor again and confirm that there are no break/monitor/trace points

**Expected behaviour**
Fixing linked and unlinked functions should behave same, keeping break/trace/monitor points after the fix.

**Comment by nicolas-dyalog** [comment]
Stops are already preserved in linkv2.1 - see issue #129 
Trace points are easy to fix.
Monitor points can be preserved but monitor timing information will be lost.

**Comment by vlnn** [comment]
What's 2.1? Releases list seems empty to me, and there are only branches for 2.0 and 1.0. Is master 2.1?

**Comment by nicolas-dyalog** [comment]
Yes, master is currently the pre-release version of Link v2.1

**Comment by nicolas-dyalog** [comment]
requires fixing Mantis 18408

**Comment by nicolas-dyalog** [comment]
This issue affect RIDE only, and monitor/trace points only.
Stops are preserved in all situations.

**Comment by nicolas-dyalog** [comment]
Fixed in v18.1 only, with Link v2.1.0-beta61
