### ISSUE TITLE
Link.Add and Link.Create induce status messages when adding or importing variables

### ISSUE THREAD

**Issue by jwied** [Dyalog/link#149]
**Describe the bug**
With Link 2.1.0-alpha I get a status messagebox with 
error AC0120: assignment is not permitted outside of a :Class or :Namespace 
Anyway, the apla-files respectively variables are created with Link.Add / Link.Create

**To Reproduce**
Steps to reproduce the behaviour:
1. Having a namespace and a folder
2. ⎕SE.Link.Create ns folder
3. ⎕SE.Link.Add varslist
4. apla-files are written correctly
5. But a status messagebox appears (with error AC0120: assignment is not permitted outside of a :Class or :Namespace)
The same thing happens, when running _Link.Create ns folder_ on a clear ws to rebuild the ws, when there are apla-files within.

**Desktop (please complete the following information):**
 - OS: Windows
 - APL version: 18.0 Unicode 64-bit ,  17.1 Unicode 32-bit
 - `⎕SE.Link.Version`: 2.0.1-alpha

**Comment by abrudz** [comment]
Could you add an example of an array that causes this behaviour?

**Comment by jwied** [comment]
You can try this with very simple variables, even numeric scalars or simple text arrays.
**Here´s a complete example for reproducing the bug:**
`       )load sqapl`
C:\Program Files\Dyalog\Dyalog APL-64 18.0 Unicode\ws\sqapl.dws saved Mon Jun  8 20:00:40 2020
`      SQA.var1←123.45`
`      SQA.var2←3 4⍴'abcd..,,'`
`       ⎕SE.Link.Export '#.SQA' 'E:\Code_myNS\'`
Exported: #.SQA → E:\Code_myNS
`       ⎕SE.Link.Create '#.SQA' 'E:\Code_myNS\'`
Linked: #.SQA ←→ E:\Code_myNS
`       ⎕SE.Link.Add '#.SQA.var1' '#.SQA.var2'`
Added: #.#.SQA.var1 #.#.SQA.var2


At this moment, this status message comes, although the files var1.apla and var2.apla have been created correctly:
line(0,0) : error AC0120: assignment is not permitted outside of a :Class or :Namespace "123.45" 
                                                                                         ^
Complete: 1 error.
line(0,0) : error AC0120: assignment is not permitted outside of a :Class or :Namespace "123.45" 
                                                                                         ^
Complete: 1 error.
line(0,0) : error AC0120: assignment is not permitted outside of a :Class or :Namespace "[" 
                                                                                         ^
line(1,1) : error AC0120: assignment is not permitted outside of a :Class or :Namespace " ('abcd')" 
                                                                                          ^
line(2,1) : error AC0120: assignment is not permitted outside of a :Class or :Namespace " ('..,,')" 
                                                                                          ^
line(3,1) : error AC0120: assignment is not permitted outside of a :Class or :Namespace " ('abcd')" 
                                                                                          ^
line(4,9) : error AC0120: assignment is not permitted outside of a :Class or :Namespace "         ]" 
                                                                                                  ^
Complete: 5 errors.
line(0,0) : error AC0120: assignment is not permitted outside of a :Class or :Namespace "[" 
                                                                                         ^
line(1,1) : error AC0120: assignment is not permitted outside of a :Class or :Namespace " ('abcd')" 
                                                                                          ^
line(2,1) : error AC0120: assignment is not permitted outside of a :Class or :Namespace " ('..,,')" 
                                                                                          ^
line(3,1) : error AC0120: assignment is not permitted outside of a :Class or :Namespace " ('abcd')" 
                                                                                          ^
line(4,9) : error AC0120: assignment is not permitted outside of a :Class or :Namespace "         ]" 
                                                                                                  ^
Complete: 5 errors.


**After a clear ws and Link.Create, the Namespace is rebuild correctly.**
`      )clear`
clear ws
`        ⎕SE.Link.Create '#.SQA' 'E:\Code_myNS\'`
Linked: #.SQA ←→ E:\Code_myNS

**But again the status message comes:**
line(0,0) : error AC0120: assignment is not permitted outside of a :Class or :Namespace "123.45" 
                                                                                         ^
Complete: 1 error.
line(0,0) : error AC0120: assignment is not permitted outside of a :Class or :Namespace "[" 
                                                                                         ^
line(1,1) : error AC0120: assignment is not permitted outside of a :Class or :Namespace " ('abcd')" 
                                                                                          ^
line(2,1) : error AC0120: assignment is not permitted outside of a :Class or :Namespace " ('..,,')" 
                                                                                          ^
line(3,1) : error AC0120: assignment is not permitted outside of a :Class or :Namespace " ('abcd')" 
                                                                                          ^
line(4,9) : error AC0120: assignment is not permitted outside of a :Class or :Namespace "         ]" 
                                                                                                  ^
Complete: 5 errors.

**Comment by nicolas-dyalog** [comment]
Acknowledged. There are several ways to address this issue, and they all have drawbacks. We need to make a decision.

**Comment by nicolas-dyalog** [comment]
Will be addressed by Mantis 18477

**Comment by nicolas-dyalog** [comment]
Fixed in Link v2.1 / Dyalog v19.0
