### ISSUE TITLE
Dyalog gives a translation error trying to use Link master in Classic 17.1

### ISSUE THREAD

**Issue by dyavc** [Dyalog/link#150]
**Describe the bug**
Dyalog gives a translation error trying to use Link master in Classic 17.1

**To Reproduce**
Steps to reproduce the behaviour:

I installed link-master as of 17 july 2020 into my 17.1 classic 32-bit directories by cp.exe -f -r * .. from 
C:/Program Files (x86)/Dyalog/Dyalog APL 17.1 Classic/link-master
(which is where I unzipped link-master.zip).

I started Dyalog 17.1 classic 32-bit:
*** Fixing "C:/Program Files (x86)/Dyalog/Dyalog APL 17.1 Classic/StartupSession/Link/Utils.apln" into ⎕SE.Link caused a T
      RANSLATION ERROR (There were errors processing the script)

**Expected behaviour**
link to work in classic if possible...

our docs say about key:  
Classic Edition: the symbol ⌸ is not available in Classic Edition, and the Key operator is instead represented by ⎕U2338.

**Desktop (please complete the following information):**
 - OS: Windows
 - APL version: 17.1.38524 Classic 32-bit
 - `⎕SE.Link.Version`: 2.1.0-alpha

**Comment by nicolas-dyalog** [comment]
Fixed
