### ISSUE TITLE
Unicode formfeed character is lost when brought back with -source=dir

### ISSUE THREAD

**Issue by dyavc** [Dyalog/link#151]
**Describe the bug**
Unicode formfeed character is lost when brought back with -source=dir

**To Reproduce**
Steps to reproduce the behaviour:
'ns' ⎕ns ''
      )cs ns
#.ns
      ⎕fx 'dummy' ('x←','''',(⎕ucs 12),'''')

      ]Link.Create #.ns c:\tmp\test -source=ns
Linked: #.ns ←→ c:\tmp\test

)off
Start Dyalog again

      ]Link.Create #.ns c:\tmp\test -source=dir
ns.dummy no longer has the unicode form feed character.

It is in the .apln file in c:\tmp\test\

**Expected behaviour**
Expect to be able to bring it back in as it was in the source function

**Desktop (please complete the following information):**
 - OS: Windows 10
 - APL version: 17.1.38524 32-bit classic and 18.0.38756 64-bit Unicode
 - `⎕SE.Link.Version`: [e.g. 2.0.1]  2.0 and 1.0 and 2.1-alpha

**Comment by dyavc** [comment]
there is a unicode or ascii 0xc in the file:  

od -Ax -X dummy.aplf
000000 6d756420 0a0d796d 86e27820 270c2790
000010 00000a0d
000012

**Comment by dyavc** [comment]
Our conclusion is that Link should not do this--should not bring unescaped control characters into text files as this will lead to problems, especially in cases where third party tools and editors are used.

**Comment by dyavc** [comment]
closing this issue

**Comment by abrudz** [comment]
Then this should be documented, warning about possible data loss. Maybe Link should even refuse to write such a function out to file, knowing that it won't round-trip?

**Comment by nicolas-dyalog** [comment]
Link v2.1 shall check for invalid characters and error.

**Comment by nicolas-dyalog** [comment]
fixed in v2.1
