### ISSUE TITLE
Editing a variable should not create a new .apla file

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/link#153]
**Description**
If a variable has not been loaded from a source file, using the editor to inspect or modify it should not cause the creation of a file.

**To Reproduce**
]link.create # /some/folder
text←'Hello' 'World'
)ed text, make a change
A file text.apla is created

**Expected behaviour**
Only the workspace should be modified, unless the variable was already backed by a file.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - APL version: 18.0 Unicode 64-bit
 - `⎕SE.Link.Version`: 2.1.0-alpha

**Comment by nicolas-dyalog** [comment]
Fixed in link v2.1
