### ISSUE TITLE
)clear does not remove existing links

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/link#154]
**Description**
On )CLEAR, Link 2.1 does not clear existing links.

**To Reproduce**
]link.create # /some/folder
)clear
]link.list
Link is still reported

**Expected behaviour**
All links should be removed on )load or )clear

**Desktop (please complete the following information):**

OS: Windows 10
APL version: 18.0 Unicode 64-bit
⎕SE.Link.Version: 2.1.0-alpha

**Comment by nicolas-dyalog** [comment]
fixed in link v2.1
