### ISSUE TITLE
:Require keyword does not work with Link 2.1

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/link#155]
[aplnfiles.zip](https://github.com/Dyalog/link/files/5284529/aplnfiles.zip)

**Describe the bug**
The :Require keyword does not work with Link 2.1

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a folder containing server.apln and engine.apln
2. ]link.create # /that/folder

line(0,9) : error AC0116: cannot read required file ":Require file://engine.apln"                                                               ^
line(2,3) : error AC0008: error (VALUE ERROR) executing line "   dup←#.engine.dup" 
Complete: 2 errors.

**Expected behaviour**
No errors, as in Link 2.0.3

**Desktop (please complete the following information):**
OS: Windows 10
APL version: 18.0 Unicode 64-bit
⎕SE.Link.Version: 2.1.0-alpha

**Comment by nicolas-dyalog** [comment]
requires fixing http://mantis.dyalog.com/view.php?id=18588

**Comment by nicolas-dyalog** [comment]
Fixed in Link v2.1 / Dyalog v19.0
