### ISSUE TITLE
Suggest renaming Link.Break to Link.Unlink

### ISSUE THREAD

**Issue by bernecky** [Dyalog/link#178]
I find that the verb Break is not very evocative. What is being broken? 
Does it perhaps mean to take a short rest?

I propose Unlink as a better name. It is evocative, in that it is evident that a link will
no longer exist once it is executed.

**Comment by nicolas-dyalog** [comment]
Unlink is less ambiguous, but not a proper English verb, so management has discarded it.
"Break" shall remain the name.

**Comment by abrudz** [comment]
Another reason is that the full name is Link.Break while Link.Unlink would be strange.
