### ISSUE TITLE
Linking to # fails

### ISSUE THREAD

**Issue by abrudz** [Dyalog/link#182]
**To Reproduce**
```
      )clear
clear ws
      ]create # /tmp/newdir -s=dir
* Command Execution Failed: ⎕SE.Link.Create: Destination namespace not empty: #.#
```
**Desktop (please complete the following information):**
 - OS: Windows
 - APL version: 19.0.39491u64
 - `⎕SE.Link.Version`: e.g. 2.0.1-beta5

**Additional context**
`#.#` looks wrong too. Link should simplify ns paths.

**Comment by nicolas-dyalog** [comment]
I can't reproduce the issue.
Can you double check that this is not a duplicate of #161 ?
- try with the latest v2.1.0-beta18
OR
- see if it still reproduces if you uncheck Options >Object-Syntax > Expose Root Properties

**Comment by nicolas-dyalog** [comment]
Fixed the formatting of the namespace name in v2.1.0-beta19

**Comment by abrudz** [comment]
Fixed.
