### ISSUE TITLE
Gracefully handle invalid dir name

### ISSUE THREAD

**Issue by abrudz** [Dyalog/link#183]
**Describe the bug**
When creating anew dir using Windows Explorer, the dir is initially named "New folder" (or the equivalent in the user's language). Link should handle this by ignoring the dir until renamed to something valid

**To Reproduce**
Create a link. Using Windows Explorer, navigate to the linked dir, then click 📂New Folder. Link suspends with:
```
1:DOMAIN ERROR
WatchEvent[14] ⎕SE.Link.Notify nargs
               ∧
```

**Expected behaviour**
Ignore the dir creation or maybe warn about it.

**Desktop (please complete the following information):**
 - OS: Windows
 - APL version: 19.0.39491u64
 - `⎕SE.Link.Version`: 2.0.1-beta5

**Additional context**
Seems that we're missing a global trap to catch unforeseen errors.

**Comment by nicolas-dyalog** [comment]
Fixed in Link v2.1.0-beta19
