### ISSUE TITLE
Add ⎕IO etc.

### ISSUE THREAD

**Issue by abrudz** [Dyalog/link#184]
**Describe the bug**
Namespace-scope system variables should be valid for Add

**To Reproduce**
Create a link to `ns`
```
      ]add ns.⎕io
Not found: #.ns.⎕io
```

**Expected behaviour**
Create `⎕IO.apla`

**Desktop (please complete the following information):**
 - OS: Windows
 - APL version: 19.0.39491u64
 - `⎕SE.Link.Version`: 2.0.1-beta5

**Additional context**
May need special handling of name clashes caused by case, and don't ever add case code.

**Comment by nicolas-dyalog** [comment]
Link.Export -arrays=⎕IO should work too
