### ISSUE TITLE
Link-Wiki doc on Import is outdated

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/link#191]
**Describe the bug**
The wiki-page about LINK.Importneeds to be update to reflect recent enhancements.

**To Reproduce**
open https://github.com/Dyalog/link/wiki/Link.Import and compare it with https://github.com/Dyalog/link/blob/master/help/Link.Import.md

**Comment by nicolas-dyalog** [comment]
will be fixed when Link v2.1 is officially released.

**Comment by nicolas-dyalog** [comment]
oops - not closed then

**Comment by mkromberg** [comment]
The documentation for versions 2.0 and 3.0 should now be correct.
