### ISSUE TITLE
]link.create hangs from time to time, have to kill -9 ps

### ISSUE THREAD

**Issue by bernecky** [Dyalog/link#193]
This just started today, with the latest version of link.

```
     ⎕SE.Link.Version
2.1.0-beta22
      
```
 I do this:

```
      )clear
clear ws
      ]link.create # Source/Root
Link Warning: ⎕SE.Link.U.UCMD_Run: .NET or .NetCore not available - Link cannot watch directory
```

and it just sits there, doing nothing (all CPUs idle[ish] if "top" is to be believed).  RIDE seems okay - help and other menu things work. Weak and/or strong interrupt have no effect, and RIDE Quit does not terminate APL, although it does ask
if that's what I want to do.  Killing APL with "kill -9 aplprocess#" makes APL go away, but RIDE still hangs.

I have to do "kill rideprocess#" to make RIDE go away. If I immediately restart APL/RIDE, it works okay.

The session log is 561550 lines long: In the past, large logs caused RIDE to go painfully slowly when
displaying output, particularly when [accidentally] displaying a large nested array, or ⍕ thereof (implying
that RIDE, not APL, is the bottleneck). I'll try running "system monitor" while I'm working, and see if 
there is, e.g, a major memory usage increase. I would blow away the session log, but I have a
rather sentimental attachment to it.

**Comment by abrudz** [comment]
If RIDE is responsive, try View → Show Debug to see if any threads are running, and if so, where they are holding.

**Comment by bernecky** [comment]
No threads. No stack. No memory usage increase.

**Comment by abrudz** [comment]
Do you have a six-space prompt? Does `2+2` give `4`?

**Comment by bernecky** [comment]
Nope. And nope.

 Like I said, it's hanging. no prompt, typing evaporates. It looks to be definitely correlated with the execution of ]link.create.

**Comment by nicolas-dyalog** [comment]
Can you please provide the exact interpreter version you're using, and the ride version if any.
Thanks.
Nic.

**Comment by bernecky** [comment]
Here ya go, Nic:

```
IDE:
  Version: 4.2.3437
  Platform: Linux x86_64
  Date: 2019-08-13 14:55:17 +0200
  Git commit: 691f47856e05a36f70847313b23e061a0cf95392
  Preferences:{
    "autoCloseBrackets":"0",
    "autoPW":"1",
    "autocompletionDelay":"250",
    "blockCursor":"1",
    "editWins":"{\"width\":1297,\"height\":628,\"x\":1346,\"y\":965,\"ox\":0,\"oy\":0}",
    "editWinsRememberPos":"1",
    "floatSingle":"0",
    "floating":"1",
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×*⍟⌹○!? |⌈⌊⊥⊤⊣⊢ =≠≤<>≥≡≢ ∨∧⍲⍱ ↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩~ ÷/\\⌿⍀ ,⍪⍴⌽⊖⍉ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬ ",
    "selectedExe":"/opt/mdyalog/17.1/64/unicode/mapl",
    "selectionHighlight":"1"
  }

Interpreter:
  Version: 18.0.39712
  Platform: Linux-64
  Edition: Unicode/64
  Date: Dec 11 2020 at 01:07:55
```

Thanks, Bob

**Comment by bernecky** [comment]
Hi, Nic,

I just tried the above ]link.create command now, and it did NOT fail. Perhaps it had something to do with the
contents of Source/Root at the time.

If I can make the failure recur, I'll copy Source/Root elsewhere and see if I can reproduce the fault in controlled circumstances.

Bob

**Comment by nicolas-dyalog** [comment]
I'll close the issue for now. Please re-open it as soon as you find a reliable repro.

**Comment by bernecky** [comment]
Will do. Thanks.
