### ISSUE TITLE
Whitespace formatting is not preserved on first fix of APL dfn/dop

### ISSUE THREAD

**Issue by RojerGS** [Dyalog/link#196]
**Describe the bug**
When fixing an APL dfn/dop for the first time, Link throws whitespace formatting out of the window.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Dyalog interpreter.
2. Create a link, e.g. with `]create # C:/tmp`.
3. Type `)ed f`.
4. Define a function, e.g. `f ← { ⍺ + ⍵ }` (plenty of whitespace for demo purposes).
5. Press ESC (to fix the function).
6. Type `)ed f`.
7. Notice the function has been reformatted to `f←{⍺+⍵}` (both in the Dyalog editor and in the `f.aplf` in the filesystem).
8. Hand-reformat to `f ← { ⍺ + ⍵ }`.
9. Press ESC (to fix the function) and pick "Fix as code in the workspace".
10. Type `)ed f`.
11. Notice that the second time around the whitespace was preserved.

**Expected behaviour**
The whitespace should not be squashed on the first fix of the function.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - APL version: Dyalog APL/W-64 Version 18.0.38756
 - `⎕SE.Link.Version`:  2.0.3

**Additional context**
Only tested this with dfns, dops and namespaces. When creating a namespace with `)ed ⍟ ns` and fixing it the whitespace is not squashed, i.e., this seems to affect only a subset of the APL objects.

**Comment by nicolas-dyalog** [comment]
Nice catch !!!

Fixed in link v2.1.0-beta25
