### ISSUE TITLE
Improve error-msg when attempting to import into unnamed ns

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/link#197]
**Describe the bug**
I had forgotten that the doc says unnamed ns were not supported and tried to Import into one. This led to the error-msg "Unable to import to namespace: #.[Namespace]" (2.0.6) or  "⎕SE.Link.Import: Not a namespace: #.[Namespace]" (2.1.0-beta23) which are both not immediately obvious.

**To Reproduce**
Steps to reproduce the behaviour:
1.  Start Dyalog
2. `foo←⎕ns''`
3. `⎕SE.Link.Import foo((+2 ⎕NQ'.' 'GetEnvironment' 'DYALOG'),'/StartupSession/Link/Watcher.apln')`

**Expected behaviour**
Error-msg should indicate that importing into unnamed namespaces is not supported.

**Desktop:**
 - OS: W10
 - APL version: 180u64.39795
 - `⎕SE.Link.Version`: various, as indicated above

**Comment by nicolas-dyalog** [comment]
Fixed in link v2.1.0-beta24
