### ISSUE TITLE
]link -? doesn't work with small ⎕PW

### ISSUE THREAD

**Issue by nicolas-dyalog** [Dyalog/link#199]
**Describe the bug**
]link -? doesn't work with small ⎕PW

**To Reproduce**
     ⎕PW←42
      ]link.add -?
     ⍝ hangs forever

      ⎕SE.Link.Version
2.1.0-beta25

**Comment by nicolas-dyalog** [comment]
⎕SE.Dyalog.Utils.reshapeText should set n⌈←0

**Comment by nicolas-dyalog** [comment]
That's a bug in spice.

**Comment by mkromberg** [comment]
Nonetheless, given the severity of the problem and the simplicity of working around it (localise ⎕PW and ensure a minimum value), I would recommend making a change to Link.

**Comment by nicolas-dyalog** [comment]
Please explain how you work around it, given that the call to reshapeText is outside the link function.

**Comment by mkromberg** [comment]
OK, I thought we had an opportunity to set ⎕PW. If not, then perhaps we check ⎕PW and return "help not available with ⎕PW<43". Better than going into an infinite loop!

**Comment by abrudz** [comment]
The `⎕SE.Dyalog.Utils` code has now been fixed.

**Comment by nicolas-dyalog** [comment]
Fixed in link v2.1.0-beta28
