### ISSUE TITLE
Classic flavour of the interpreter

### ISSUE THREAD

**Issue by lstefano71** [Dyalog/link#20]
Please: make ]link (and its test suite) work in the classic interpreter. At the moment there are assumptions in the code. For instance: Test.onWrite (https://github.com/Dyalog/link/blob/master/Test.dyalog#L216) neglects to test for 82...

**Comment by mkromberg** [comment]
Link QA script (Link.Test.Run now runs under - and will continue to be tested under - Classic)

**Comment by lstefano71** [comment]
Close, but no cigar. 
![image](https://user-images.githubusercontent.com/2143482/55416936-029c3300-5570-11e9-949c-05e0e8a0cdaa.png)

This is with commit https://github.com/Dyalog/link/commit/f8106ebe80b3f0ec06b293267480755e0e7c7420

**Comment by lstefano71** [comment]
Here's where it crashes.

![image](https://user-images.githubusercontent.com/2143482/55417319-c74e3400-5570-11e9-9510-3cdfcccb72ef.png)

**Comment by abrudz** [comment]
D'oh of course, since we use `⎕NGET` we don't get `⎕FIX's automatic translation to `⎕Unnn` and startup.dyalog has both `⊆` and `⍠`
