### ISSUE TITLE
]link.add name←value

### ISSUE THREAD

**Issue by abrudz** [Dyalog/link#202]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I work in the session, making variable and one-liner dfn assignments only to forget to `]add` my new stuff.

**Describe the solution you'd like**
I'd like to combine the steps of assignment and adding things. `]add name←value` [would make sense](https://chat.stackexchange.com/transcript/message/56742479#56742479). Maybe there also needs to be a way to effect this for multi-line input.

**Describe alternatives you've considered**
I've considered a trigger, but that would pick up on too much and slow everything down.

**Comment by nicolas-dyalog** [comment]
You can achieve this exact effect with (ns name ⎕SE.Link.Fix source).
It will fix it AND add it to the link, all at once.
Note that ⎕SE.Link.Add simply call ⎕SE.Link.Fix with empty source.
Nic.
