### ISSUE TITLE
Link.Create can fail with a VALUE ERROR if a previously linked namespace is deleted

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/link#204]
**Describe the bug**
Link.Create can fail with a VALUE ERROR if a previously linked namespace is deleted.

**To Reproduce**
Steps to reproduce the behaviour:
```
      )clear
      ]link.create myns /tmp/myns
Linked: #.myns ←→ C:\tmp\myns
      ⎕ex 'myns'
      ]link.create otherns /tmp/myns
* Command Execution Failed: VALUE ERROR
```

**Expected behaviour**
Automatic deletion of the old link (which seems to happen if you ask for ]link.status).

**Version:**
 - `⎕SE.Link.Version`: 2.1.0-beta27

**Comment by nicolas-dyalog** [comment]
Fixed in link v2.1.0-beta32
