### ISSUE TITLE
Link should ignore changes to files that are not APL source files

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/link#207]
**Describe the bug**
Link should only try to process files that have one of the supported file extensions.

**To Reproduce**
Do something to a configuration file, see a warning along the lines of:
Link Warning: ⎕SE.Link.Notify: renamed C:/Devt/sbo/back/dyalog.dcfg: invalid name defined by file: C:/Devt/sbo/back/dyalog.dcfg

**Expected behaviour**
The change should be ignored.

**Desktop (please complete the following information):**
- Windows 18.1.39738.0 64 Unicode
 - `⎕SE.Link.Version`: 2.1.0-beta22

**Comment by nicolas-dyalog** [comment]
Fixed in link v2.1.0-beta40
