### ISSUE TITLE
Classes (their scripts) are destroyed by a ]link -reset

### ISSUE THREAD

**Issue by lstefano71** [Dyalog/link#22]
Try the following:

Create a class and put anything you want in it:
```
      )ed ○class
```
Then execute the following:
```
      ]link # d:\trash\wrapper\source\
 # linked to d:/trash/wrapper/source/ 
      )ed class
      ]link -reset
 Link from # to d:/trash/wrapper/source/ removed (2 names affected) 
```

Now try:
```
     )ed class
```
again... Surprise! The script is gone!

**Comment by dyavc** [comment]
Hi Stefano, 

I confirm that I can reproduce this issue with ]link version 1.15 of 23 Oct 2018.

Regards,

Vince
