### ISSUE TITLE
]link.create should not attempt to export names of class n.6 (external class)

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/link#220]
**Describe the bug**
]link.create reports errors if the namespace contains external objects.

**To Reproduce**
Steps to reproduce the behaviour:
⎕USING←''
System.Environment.Version
Verify that 9.6 = ⎕NC ⊂'System.Environment'
]link.create # /some/folder
Notice output includes:
1 export(s) failed:
#.System.Environment

**Expected behaviour**
Names of class n.6 should not be attempted exported.

`⎕SE.Link.Version`: 2.1.0-beta40

**Comment by mkromberg** [comment]
What would be really nice was if we could find a way to not create an empty "System" folder for the namespace which *only* contains the un-exportable name Environment, but for this we need an interpreter enhancement that allows us to determine that a namespace was created in order to map an external namespace. Watch this space.

**Comment by nicolas-dyalog** [comment]
Fixed in Link v2.1.0-beta41
