### ISSUE TITLE
Error "Can't Edit: The value of the name has changed." with ]LINKed files

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/link#221]
**Describe the bug**
While working with ]LINKed files and editing suspended code, that "old" error sometimes still show up.

**To Reproduce**
Steps to reproduce the behaviour:
1. `)clear`
2. `]link.create # c:/temp/test`
3. `)ed ⍟test`
```

:Namespace test

    ∇ R←f1
      R←sub1
    
      ∘∘∘
    ∇


    ∇ R←sub1

      ∘∘∘


    ∇


:EndNamespace

```
fix that and repeat these step, but use the name test1.

4. `test.f1`
when it crashes in sub1, do an edit and change sub1 (inserting/removing blank lines is sufficient). Make sure execution continues and you get out of sub1. When f1 crashes, try to edit it. You should now see the error-message: 
![image](https://user-images.githubusercontent.com/5645494/107937849-ccf66c80-6f84-11eb-966d-79574d6fe780.png)

**Expected behaviour**
This problem does not show up when editing a class with suspended code in the workspace in unlinked state. I'd expected the same behavior when ]LINK is used.

**Desktop (please complete the following information):**
Dyalog  18.1.40004 64-bit Unicode, BuildID bf80af4f            
 OS      Windows 10 or Windows Server 2016 (10.0.19041) 64-bit  
 SALT    2.808, Link: 2.1.0-beta41                              
 UCMD    2.4                                                    
 .NET    .NET Core 3.1.12                                       
 WS      18.1

**Comment by mbaas2** [comment]
Argh - repro fails. ws must have been in some strange state already  when this started :((
My repro was only based on )clearing the interpreter, but I never reloaded...

**Comment by mbaas2** [comment]
I gave up too early! The repro works reliably here...

**Comment by nicolas-dyalog** [comment]
Reported and fixed as Mantis 18873
