### ISSUE TITLE
)clear does not shut down file system watchers

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/link#225]
**Describe the bug**
When doing )CLEAR in a ]LINKed ws, it seems there are still file system watchers active & watching the once linked folder.

**To Reproduce**
````
      3⎕MKDIR'c:\temp\210220\Test1\foo'
      ]link.create # c:\temp\210220\Test1
      )ed goo
````
create some content for that fn
````     
      )clear
      ]link.create # c:\temp\210220\Test1\foo
      'Plus←{⍺+⍵}'⎕nput'c:\temp\210220\Test1\hoo.aplf'
````
will produce output of these 2 lines:
````
Link Warning: ⎕SE.Link.Notify: created c:/temp/210220/Test1/hoo.aplf: path not in a linked directory
Link Warning: ⎕SE.Link.Notify: changed c:/temp/210220/Test1/hoo.aplf: path not in a linked directory
````
**Expected behaviour**
`)clear` should also shut down the fsws it cxreated.

**Desktop (please complete the following information):**
Dyalog  18.1.40004 64-bit Unicode, BuildID bf80af4f            
 OS      Windows 10 or Windows Server 2016 (10.0.19041) 64-bit  
 SALT    2.808, Link: 2.1.0-beta41                              
 UCMD    2.4                                                    
 .NET    .NET Core 3.1.12                                       
 WS      18.1

**Comment by nicolas-dyalog** [comment]
Due to Mantis 18903
Work around coded in Link v2.1.0-beta52
