### ISSUE TITLE
]link.create should succeed if the namespace and directory both exist but have identical content

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/link#230]
If a link has been successfully created, then ]link.break followed by repeating the original ]link.create should succeed, rather than report:

`Error: ⎕SE.Link.Create: Cannot link a non-empty namespace to a non-empty directory: #.stats ←→ c:\tmp\stats`

`⎕SE.Link.Version`: 2.1.0-beta51

**Comment by nicolas-dyalog** [comment]
Fixed in link v2.1.0-beta67
