### ISSUE TITLE
Link.Create with casecode does not read in a previously created function 

### ISSUE THREAD

**Issue by dyavc** [Dyalog/link#231]
**Describe the bug**
Link.Create with casecode does not read in a previously created function 

**To Reproduce**

Steps to reproduce the behaviour:
Using d:/temp or c:/temp/ as an example directory, but modify to suit your directory structure please

delete c:/temp/Selektor if it exists from previous tests

)ns #.Selektor
)ns #.Selektor.Meldung
)ed #.Selektor.Meldung.Meldung

]Link.Create #.Selektor c:/temp/Selektor -source=ns  -watch=both -casecode -forcefilenames

)clear

⍝⍝⍝Reload it , but with -source=dir

]Link.Create #.Selektor c:/temp/Selektor -source=dir  -watch=both -casecode -forcefilenames
⍝⍝ V: I get a warning here : 1 import(s) failed:
⍝⍝  c:\temp\Selektor\Meldung-1\Meldung.Meldung-401.aplf                                                           
⍝ modify function
)ed #.Selektor.Meldung.Meldung

⍝⍝⍝ now get some warnings

V: result is another file meldung.meldung-401.aplf

or customer reports:
D:  result is another folder meldung-1-1 with a Meldung-1-1.aplf file in it (picture2.png) (

**Expected behaviour**
I think that we expect the existing aplf file to be opened and saved 

**Screenshots**

**Session transcript**
If applicable, copy your log in to help explain your problem.
 )ns #.Selektor
#.Selektor
)ns #.Selektor.Meldung
#.Selektor.Meldung
)ed #.Selektor.Meldung.Meldung
      ]Link.Create #.Selektor d:/temp/Selektor -source=ns  -watch=both -casecode -forcefilenames
Error: ⎕SE.Link.Create: Destination directory not empty: d:/temp/Selektor
      ]Link.Create #.Selektor d:/temp/Selektor -source=ns  -watch=both -casecode -forcefilenames
Linked: #.Selektor ←→ d:\temp\Selektor
      )clear
clear ws
      ]Link.Create #.Selektor d:/temp/Selektor -source=dir  -watch=both -casecode -forcefilenames
Linked: #.Selektor ←→ d:\temp\Selektor                                                                        
1 import(s) failed:                                                                                           
d:\temp\Selektor\Meldung-1\Meldung.Meldung-401.aplf                                                           
      )ed #.Selektor.Meldung.Meldung

      ⎕se.Link.Version
2.1.0-beta51

**Desktop (please complete the following information):**
Windows 10
link 2.1.0-beta51, with 18.0.40044 32-bit classic

**Additional context**

**Comment by nicolas-dyalog** [comment]
Fixed in link v2.1.0-beta54
