### ISSUE TITLE
Link fails with a VALUE ERROR on directories with invalid names

### ISSUE THREAD

**Issue by abrudz** [Dyalog/link#233]
This is due to [`IsRootName`](https://github.com/Dyalog/link/blob/master/StartupSession/Link/Utils.apln#L346) only trapping error 11 (DOMAIN ERROR), but `⎕WG` gives error 6 (VALUE ERROR) on invalid names.

**Comment by nicolas-dyalog** [comment]
This is a solution, not a problem.
Please provide a repro, and version information.

Link fails gracefully on weird directory names as far as I can tell.
      ⎕SE.Link.Version
2.1.0-beta53
      3 ⎕MKDIR '/tmp/sdfadsfasdfs/a+b'
       ]link.create # /tmp/sdfadsfasdfs
Linked: # ←→ /tmp/sdfadsfasdfs
1 import(s) failed:           
/tmp/sdfadsfasdfs/a+b/        
      
      3 ⎕MKDIR '/tmp/sdfadsfasdfs/a+b=c'
Link Warning: ⎕SE.Link.Notify: created /tmp/sdfadsfasdfs/a+b=c: invalid name defined by file: /tmp/sdfadsfasdfs/a+b=c
Link Warning: ⎕SE.Link.Notify: created /tmp/sdfadsfasdfs/a+b=c: invalid name defined by file: /tmp/sdfadsfasdfs/a+b=c
