### ISSUE TITLE
False alarm issued on ⎕SE.Link.Expunge

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/link#235]
If you use Link.Expunge to delete an object, you get a warning:

```
      ⎕SE.Link.Expunge 'linkdemo.ns'
Link Warning: ⎕SE.Link.Notify: deleted C:/tmp/linkdemo/ns.apln: could not determine which object was linked to it
```

I don't think this warning is ever useful, if a file is deleted and there is no corresponding object in the workspace, Link should not worry and be happy that everything seems OK.

`⎕SE.Link.Version`: 2.1.0-beta56

**Comment by nicolas-dyalog** [comment]
Fixed in v2.1.0-beta57
