### ISSUE TITLE
Link reports a spurious error if you change a linked function which has a comment in its header line

### ISSUE THREAD

**Issue by dyavc** [Dyalog/link#244]
**Describe the bug**
Link reports a spurious error if you change a linked function which has a comment in its header line

**To Reproduce**
Steps to reproduce the behaviour:

)ns myns
#.myns
      )cs myns
#.myns
      
      ⎕fx 'goo ⍝' '3 3 3'
      )cs
#
      ]link.create #.myns d:\temp\test 
Linked: #.myns ←→ d:\temp\test

      )ed myns.goo

make any change, like adding another number to line 1 
and hit <EP> to fix and quit

Link Warning: ⎕SE.Link.Notify: changed d:/temp/test/goo.aplf: invalid file contents
Link Warning: ⎕SE.Link.Notify: changed d:/temp/test/goo.aplf: invalid file contents

**Expected behaviour**
expect it to save without errors

**Desktop (please complete the following information):**
⎕se.Link.Version
2.1.0-beta57
(got link from github on 17 Mar 2021, 15:45 )

      ]tools.version
 Dyalog  18.0.40044 32-bit Classic, BuildID 972a5b3a            
 OS      Windows 10 or Windows Server 2016 (10.0.19041) 32-bit  
 SALT    2.808, Link: 2.1.0-beta57                              
 UCMD    2.4                                                    
 .NET    .NET Framework 4.8.4300.0                              
 WS      18.0

**Comment by nicolas-dyalog** [comment]
Fixed in Link v2.1.0-beta59
