### ISSUE TITLE
Get errors after modifying a function after linking to an existing directory with -casecode and -watch=both 

### ISSUE THREAD

**Issue by dyavc** [Dyalog/link#246]
**Describe the bug**
Get errors after modifying a function after linking to an existing directory with -casecode and -watch=both .

The filename of the function is wrong.  

**To Reproduce**
I use a d:\temp\test\

PREP:      
)ns MyNs
#.MyNs

      )ed MyNs.Func1
⍝ Here, make a small change and <EP>

       ]link.create #.MyNs d:\temp\test\MyNs -casecode -source=ns -watch=both
Linked: #.MyNs ←→ d:\temp\test\MyNs

      )clear
clear ws

REPRO:
 ]link.create #.MyNs d:\temp\test\MyNs -casecode -source=dir -watch=both
Linked: #.MyNs ←→ d:\temp\test\MyNs

      )ed MyNs.Func1

⍝ make a change and <EP>,  Choose top option Fix as code

Link Warning: ⎕SE.Link.Notify: changed d:/temp/test/MyNs/Func1-1-1.aplf: invalid name defined by file: d:/temp/test/MyNs/Func1-1-1.aplf
Link Warning: ⎕SE.Link.Notify: created d:/temp/test/MyNs/Func1-1-1.aplf: invalid name defined by file: d:/temp/test/MyNs/Func1-1-1.aplf

**Expected Behaviour**
Please note that it works if you use -watch=ns after the )clear:
]link.create #.MyNs d:\temp\test\MyNs -casecode -source=dir -watch=ns

The file is named Func1-1.aplf

**Desktop (please complete the following information):**
Dyalog  18.0.40044 32-bit Classic, BuildID 972a5b3a            
 OS      Windows 10 or Windows Server 2016 (10.0.19041) 32-bit  
 SALT    2.808, Link: 2.1.0-beta57                              
 UCMD    2.4                                                    
 .NET    .NET Framework 4.8.4300.0                              
 WS      18.0

**Comment by nicolas-dyalog** [comment]
Fixed in Link2.1.0-beta60
