### ISSUE TITLE
Renaming an existing linked function does not save the new name and discards changes made 

### ISSUE THREAD

**Issue by dyavc** [Dyalog/link#247]
**Describe the bug**
Renaming an existing linked function does not save the new name in the new file and discards any changes made

**To Reproduce**
 )ns #.Myns

      )ed #.Myns.Func

⍝⍝⍝ add some code such as 1 2 3 to it on separate lines

      ]Link.Create #.Myns d:\temp\test -source=ns -watch=ns -casecode
Linked: #.Myns → d:\temp\test

      )ed #.Myns.Func

⍝⍝⍝ Rename Func to be Func1, and make a change such as adding 1 in front of each number, e.g. 11 12 13 to it

      (⎕NINFO ⎕U2360 1)'d:\temp\test\*'
  d:/temp/test/Func-1.aplf  d:/temp/test/Func1-1.aplf  

      ⎕NGET 'd:/temp/test/Func1-1.aplf'
  Func                               
 1                                   
 2                                   
 3                                   
  UTF-8-NOBOM  13 10                 

**Expected behaviour**
Expect a new function named Func1 with the changes made in it

This does happen if you )ed #.Myns.Func2 where Func2 does not exist and will be a new function

**Desktop (please complete the following information):**
]tools.version
 Dyalog  18.0.40044 32-bit Classic, BuildID 972a5b3a            
 OS      Windows 10 or Windows Server 2016 (10.0.19041) 32-bit  
 SALT    2.808, Link: 2.1.0-beta60                              
 UCMD    2.4                                                    
 .NET    .NET Framework 4.8.4300.0                              
 WS      18.0

**Comment by nicolas-dyalog** [comment]
fixed in link v2.1.0-beta68
