### ISSUE TITLE
Link create fails with a value error if you use fastload

### ISSUE THREAD

**Issue by dyavc** [Dyalog/link#249]
**Describe the bug**
Link create fails with a value error if you use fastload

**To Reproduce**
)ns Myns

      )ns Myns.Myns1

      ]Link.Create #.Myns d:\temp\test -casecode -source=ns -sysvars

      )clear

      ]Link.Create #.Myns d:\temp\test -casecode -source=dir -fastload
Error: VALUE ERROR

**Desktop (please complete the following information):**
]tools.version
 Dyalog  18.0.40044 32-bit Classic, BuildID 972a5b3a            
 OS      Windows 10 or Windows Server 2016 (10.0.19041) 32-bit  
 SALT    2.808, Link: 2.1.0-beta60                              
 UCMD    2.4                                                    
 .NET    .NET Framework 4.8.4300.0                              
 WS      18.0

**Comment by nicolas-dyalog** [comment]
Fixed in link v2.1.0-beta63
