### ISSUE TITLE
]link.create with -fastload does not detect name clashes

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/link#251]
**Describe the bug**
-fastLoad fails to detect easily detectable name clashes.

**To Reproduce**

   folder←'c:/tmp/testfastload'
   (⊂'r←dup x' 'r←x x')⎕NPUT folder,'/dup.aplf'
   (⊂'r←dup x' 'r←x x')⎕NPUT folder,'/dup.dyalog'   

⍝ Without -fastLoad, the attempt to link fails as expected:

      ]link.create # c:/tmp/testfastload
Error: ⎕SE.Link.Create: Files produce clashing APL names:
 c:\tmp\testfastload\dup.aplf    ←→  #.dup               
 c:\tmp\testfastload\dup.dyalog  ←→  #.dup     

⍝ With fastload:

      ]link.create # c:/tmp/testfastload -fastload
Linked: # ←→ c:\tmp\testfastload
      )fns
dup   

**Expected behaviour**
An error message along the lines of
"Directory c:/tmp/testfastload contains 2 source files but only 1 name was defined: name conflict suspected."

**Desktop (please complete the following information):**
 - OS: Windows
 - APL version:  18.1.40275
 - `⎕SE.Link.Version`: 2.1.0-beta61

**Comment by abrudz** [comment]
I thought the whole purpose of fastload was to not do any sanity checks.

**Comment by nicolas-dyalog** [comment]
Fixed in link v2.1.0-beta64
