### ISSUE TITLE
Import fails to import certain files

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#253]
Deep inside Link uses a utility `SniffScript` which is buggy:

```
      ⊢ SniffScript 'Commit' (⊂'Commit')
Commit 3.1
      ⊢ SniffScript 'Commit' (⊂'Commit⍝')
0
```

As a consequence `Import` fails to import _anything_ that has a trailing `⍝` on the first line

I am on 2.1.0-beta57

(For my record: <01840>)

**Comment by nicolas-dyalog** [comment]
Duplicate of #244 - fixed in Link v2.1.0-beta59
