### ISSUE TITLE
OnFix-Error when editing unlinked Code

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/link#257]
**Describe the bug**
LINK causes an error in OnFix when I edit a file in a )CLEAR ws (w/o using ]LINK)

**To Reproduce**
Steps to reproduce the behaviour:
1. Start Dyalog
2. )ed /tmp/foo.aplf
3. Enter some code and fix the fn.
4. Error: OnFix: `Cannot get source of #.[Namespace].c:\tmp\foo.aplf: Invalid name class (1)`

**Expected behaviour**
Would not expect LINK to do anything when nothing is linked.

**Desktop (please complete the following information):**
 Dyalog  18.1.40404 64-bit Unicode, BuildID 2693ee64            
 OS      Windows 10 or Windows Server 2016 (10.0.19042) 64-bit  
 SALT    2.9, Link: 2.1.0-beta61                                
 UCMD    2.5                                                    
 .NET    .NET Core 3.1.14                                       
 WS      18.1

**Comment by nicolas-dyalog** [comment]
Fixed in link v2.1.0-beta73
