### ISSUE TITLE
Use ⎕C if available

### ISSUE THREAD

**Issue by abrudz** [Dyalog/link#258]
`819⌶` is deprecated and may be removed shortly. Use `⎕C` if available.

Code:
* https://github.com/Dyalog/link/blob/c25c2929768d7dbb21b9ab302b527007e6262a8d/StartupSession/Link/Status.aplf#L33
* https://github.com/Dyalog/link/blob/c25c2929768d7dbb21b9ab302b527007e6262a8d/StartupSession/Link/Utils.apln#L42
* https://github.com/Dyalog/link/blob/c25c2929768d7dbb21b9ab302b527007e6262a8d/StartupSession/Link/Utils.apln#L43
* https://github.com/Dyalog/link/blob/c25c2929768d7dbb21b9ab302b527007e6262a8d/StartupSession/Link/Test.dyalog#L238
* https://github.com/Dyalog/link/blob/c25c2929768d7dbb21b9ab302b527007e6262a8d/StartupSession/Link/Test.dyalog#L243

**Comment by nicolas-dyalog** [comment]
Fixed in link v2.1.0-beta74
