### ISSUE TITLE
WIBNI: Link.Create informs about newly created directories

### ISSUE THREAD

**Issue by rikedyp** [Dyalog/link#264]
**Is your feature request related to a problem? Please describe.**
When I am unsure of the folder name or write a type, a Link is successfully created and a new folder is created on the file system. However, the output
```APL
Linked: # ←→ C:\p\NeuralNets
```
is the same whether I am linking to an existing directory or a newly created one

**Describe the solution you'd like**
Some kind of indication that the linked folder was newly created
```APL
Linked: # ←→ C:\p\NeuralNets [Directory was created]
```

**Describe alternatives you've considered**
Knowing what things are called

**Comment by mkromberg** [comment]
Fixed in 3.0.2
