### ISSUE TITLE
]Link.Break without args/parameters generates a message open to misinterpretation

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/link#266]
When I call ]link.Break, the message is get is "No link to break" .. but I have links .. that is to me most confusing.

     'andys'⎕ns''
      ]link.create andys xx
Linked: #.andys ←→ /home/andys/xx
      ]link.Status
 Namespace  Directory       Files
 #.andys    /home/andys/xx      0
      ]link.Break
No link to break
      )cs andys
#.andys
      ]link.Break
No link to break

Isn't the problem that I've not given any args/parms, rather than that there are no links to break ?

      ]version
 Dyalog  18.1.40586 64-bit Unicode, BuildID 76de2474
 OS      Linux 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64
 Link    2.1.0-beta86
 SALT    2.9
 UCMD    2.5
 .NET    .NET Core 3.1.13
 WS      18.1

**Comment by nicolas-dyalog** [comment]
Fixed in Link v2.1.0-beta88
