### ISSUE TITLE
⎕SE∧.= {⍵.##}⍣≡⊢2⊃¨5177⌶⍬ generates a SYNTAX ERROR (⎕se.Link.Test.test_bugs[254] causing the call to assert to fail

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/link#268]
⎕se.Link.Test.Run''
..
assertion failed: ⎕SE∧.= {⍵.##}⍣≡⊢2⊃¨5177⌶⍬ ⍝ at ⎕SE.Link.Test.test_bugs[254]
test_bugs[254] assert'⎕SE∧.= {⍵.##}⍣≡⊢2⊃¨5177⌶⍬'  ⍝ no more links in #

Adam says the problem is that ⎕null.## is now an error as ⎕null is now (correctly) nothing like a namespace.

I also wonder if the tests should start by checking that 5177⌶⍬ returns an empty vector .. get wrong results if something like issue #267 were to happen.

 Dyalog  18.1.40580 64-bit Unicode, BuildID 65f04447            
 OS      Windows 10 or Windows Server 2016 (10.0.19041) 64-bit  
 Link    2.1.0-beta86                                           
 SALT    2.9                                                    
 UCMD    2.5                                                    
 .NET    .NET Framework 4.8.4341.0                              
 WS      18.1

**Comment by nicolas-dyalog** [comment]
Fixed in Link v2.1.0-beta87
