### ISSUE TITLE
File system watcher: documentation issue

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#276]
Regarding **Integrating External Changes**: the documentation says:

_"This functionality is currently only available under Microsoft Windows, but the intention is to extend support to all platforms."_

Elsewhere it is stated that this functionality requires .NET or .NET Core.

Does that mean that it works under Linux in case .NET Core in installed?

Does that mean that it would not work under Windows if no .NET is available, although Windows without .NET might be impossible anyway.

In any case the documentation should be explicit on this.

**Comment by mkromberg** [comment]
I believe this has been fixed in the new documentation. Please reopen the issue with an exact page reference, if you can still find this or a similar statement.
