### ISSUE TITLE
Confusing message when adding a function via )ED

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#278]
When a function is added to a linked namespace via the editor then this message is printed to `⎕SE`:

```
Link Warning: ⎕SE.Link.Notify: created /path/funcname: ignoring attempt to redefine #.{nsname}.{fnname} which is linked to /path/
```
That is everything but helpful.

**Comment by aplteam** [comment]
The message is provided only when a first object is added to a new namespace.

**Comment by mkromberg** [comment]
I am unable to reproduce this, please reopen the issue if you are able to provide a complete, reproducible example.
