### ISSUE TITLE
ReSync prodcues a confusing Msg after deleting a file in a linked folder

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#279]
```
NOTE: 4 change must be resolved by hand before -proceed is possible         
....
```

Apart from not using the plural it has already deleted the object from the workspace that I did delete in the folder beforehand. Since there was no other change the message is misleading: there is nothing left to proceed with anyway.

But my guess is that this is a bug: since a conflict was detected Link should, according to the documentation, not do anything until the conflict is solved.

**Comment by aplteam** [comment]
Turns out it also performs renaming operations.

**Comment by mkromberg** [comment]
Unable to reproduce. Please reopen with a reproducible example if the error persists after the latest round of fixes.
