### ISSUE TITLE
Expunge does not handle fully qualified names correctly

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#334]
When `Expunge` is called from a specific namespace on, say, `Foo` then it works out the full path correctly.

When instead a fully qualified path is specified as in 

```
⎕se.Link.Expunge '#.MyNS.Foo'
````

then it still tries to work out where is was called from. That may result in something like this:

```
#.MyApp.MySubNS.#.MyApp.Helpers.Foo
```
In this case the `#.MyApp.MySubNS.` is superfluous but does not do any harm.

But of course the call might come from the instance of a class,  and that would result in something like

```
#.MyApp.[MyInstance].#.MyApp.Helpers.Foo
```

And this is invalid, so the bug needs fixing.

I have changed line 12 of the `Expunge` function so that is reads:

```
nc←container U.NameClass name←(⍕container){(1⊃⍵)∊'#⎕':⍵ ⋄ ⍺,'.',⍵}i⊃names
```

That fixes the problem.

For the record: this is my `<01919>`

**Comment by mkromberg** [comment]
Fixed by commit 1a5f060
