### ISSUE TITLE
Remove code for experimental USE_NQ switch

### ISSUE THREAD

**Issue by dyavc** [Dyalog/link#350]
**Describe the bug**
As an experiment:  If I set Watcher USE_NQ←1, Link stops working

**To Reproduce**
edit "C:\Program Files\Dyalog\Dyalog APL-64 18.0 Unicode\StartupSession\link\Watcher.apln"

USE_NQ←1

start Dyalog

In a clear WS, try to create a link to any directory you have previously linked to.
]link.create # d:/git/test4
ERRORS ENCOUNTERED: LENGTH ERROR: There was an error processing the property at position 1 of the right argument

**Desktop (please complete the following information):**
]tools.version
 Dyalog  18.0.44437 64-bit Unicode, BuildID 71dccc2b            
 OS      Windows 10 or Windows Server 2016 (10.0.19043) 64-bit  
 Link    3.0.0                                                  
 SALT    2.808                                                  
 UCMD    2.51                                                   
 .NET    .NET Framework 4.8.4400.0                              

**Additional context**
I am doing an experiment for issue #343 
to break a Link makes Dyalog hang when the namespace does not exist anymore

**Comment by mkromberg** [comment]
I'm going to close this issue: USE_NQ was an experiment. It is not tested, documented, or supported, nor is there currently any intention to do so. I am hoping the interpreter bug that made the experiment necessary will soon be fixed,

**Comment by mkromberg** [comment]
I have reopened the issue after changing the title, the code should be removed.
