### ISSUE TITLE
}LINK.Create has a modified -sysvars, doc calls it "-sysVars"

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/link#367]
**Describe the bug**
`]LINK.Create -?' shows the help:
````
]LINK.Create <ns> <dir> ...[-sysvars] ...
````

The [help](https://dyalog.github.io/link/3.0/API/Link.Create/#sysvars) indicates that this modifier should be spelled "`sysVars`".

**Comment by mkromberg** [comment]
This may not be a great decision, but it *is* documented at https://dyalog.github.io/link/3.0/API/ that

**Although option names are case sensitive and some of them contain uppercase letters when provided to API functions via option namespaces, the user command option names are entirely lowercase, to make interactive use more convenient.**
