### ISSUE TITLE
Changing the casing of a name causes trouble in non-case-sensitive file systems

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#369]
Imagine you change the name of a Linked function `Foo` to `FOO`.

That is handled correctly on non-Windows platforms but fails under Windows because this line from the `Relocate` function won't work:

```
r,←nextto ⎕NMOVE nextfrom
```

Under Windows, `nextto` and `nextfrom` are considered to be the same name, so the file already exists and an error is thrown.

One way to solve this seems to be to move the file to a temp directory and then back with the correct name.

I am on Link 3.0.2

**Comment by mkromberg** [comment]
This only fails if you have set -forcefilenames
