### ISSUE TITLE
Export should have a switch to export arrays

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/link#37]
Link should implement a prototype of the proposed "Array Notation Mk III", as described in [Adams Belfast Presentation](https://www.dyalog.com/uploads/conference/dyalog18/presentations/D04_Array_Notation_Mk_III.pdf.)

**Comment by abrudz** [comment]
[Serialise](https://github.com/abrudz/apl-array-notation/blob/master/Serialise.dyalog) takes an array and creates the notation representing it.

[Deserialise](https://github.com/abrudz/apl-array-notation/blob/master/Deserialise.dyalog) takes notation and evaluates it to an APL array.

**Comment by mkromberg** [comment]
Fixed in 64d827987e1712b8e555cd386b4643fd232c2fd4.

**Comment by lstefano71** [comment]
)clear
aaa←'test'
]link.export # d:\trash\wrapper\src2

does not export the variable. Is this the expected behaviour? How am I supposed to create the .apla file starting from the variables in my workspace?

**Comment by mkromberg** [comment]
Sorry, #21 is still open, and as a result claiming that #37 is closed was a bit premature. Any day now, I hope.

**Comment by nicolas-dyalog** [comment]
This should definitely be doable

**Comment by nicolas-dyalog** [comment]
fixed in Link v2.1.0-beta9
