### ISSUE TITLE
⎕SE.Link.Expunge crashes on scalars

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#387]
**Describe the bug**
```
⊣⎕SE.Link.Expunge 'q'
```
results in a RANK ERROR.

**Comment by mkromberg** [comment]
I am unable to reproduce this in Link 3.0.8. Which version are you using?

**Comment by aplteam** [comment]
3.0.8!

Did you really try the API function? The user command works.

**Comment by mkromberg** [comment]
Yes, I did. But I had not created a Link, as the repro didn't mention that this was necessary ;-).

**Comment by mkromberg** [comment]
Fixed in v3dev branch, awaiting review before commit to master.
