### ISSUE TITLE
When firing up an instance of 18.0, Link provides an error message

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#389]
**Describe the bug**

During the Dyalog startup process this message appears on my Windows machine:

```
*** Fixing "C:/Program Files/Dyalog/Dyalog APL-64 18.0 Unicode/StartupSession/Link/Watcher.apln" into ⎕SE.Link caused a DOMAIN ERROR (There were errors processing the script)
```
When I start a session from Ride I get additional information in a window named "Status output":

```
line(270,4) : error AC0008: error (VALUE ERROR) executing line "    ErrorCrawler←'⎕SE.Link.Crawler'∘##.U.Error" 
∧
Complete: 1 error.
```

(Note that the caret is in the wrong position)

I don't see this in the ODE despite the fact that I have the Tools > Autostatus menu item ticked.

I have no idea how to collect more information because when I force Dyalog at an early stage to stop in `WSLoaded[5]` then the error message makes no appearance.

```
 Dyalog  18.0.44659 64-bit Unicode, BuildID beef5c8d            
 OS      Windows 10 or Windows Server 2016 (10.0.19043) 64-bit  
 Link    3.0.8                                                  
 SALT    2.808                                                  
 UCMD    2.51                                                   
 .NET    .NET Framework 4.8.4420.0                              
 WS      18.0                                                   
```

**Comment by e9gille** [comment]
The status window is suppressed, but still appears in RIDE (see https://github.com/Dyalog/ride/issues/529).
Not sure about the caret position, but feel free to log an issue on RIDE for that.

**Comment by mkromberg** [comment]
The error that is occurring was issue #331, which was fixed in September: https://github.com/Dyalog/link/commit/f330e90219de702d177e28f5e8bf157a. I suspect you have your system set up so that Dyalog APL is first loading an old version of Link which still has the issue, and then overwriting it with Link 3.0.8, which does not have the error.

**Comment by mkromberg** [comment]
Closing this issue now, remaining work on Status Windows etc belongs in the RIDE project.
