### ISSUE TITLE
]link.create/export create files with the wrong name

### ISSUE THREAD

**Issue by lstefano71** [Dyalog/link#39]
Repro: in a clear WS create an empty class, like aaa.
      )ed ○aaa

Escape immediately to leave the class empty (the content is not relevant).
Then try and export the root:
      ]link.export # d:\trash\wrapper\src1
Exported: # → d:\trash\wrapper\src1

This is the content of the generated folder:

![image](https://user-images.githubusercontent.com/2143482/55420264-e3ed6a80-5576-11e9-97b6-9f380b0a53e8.png)

There are two files, and not one, as expected. And the one that is supposed to be aaa.aplc is called aaadyalog (no "." between name and extension and wrong extension).

**Comment by e9gille** [comment]
The issue with the missing `.` before `dyalog` has been fixed in #44 

The other issue manifests only on Export (`ôpts.aplo`)

**Comment by abrudz** [comment]
Fixed.
