### ISSUE TITLE
Warning "invalid file contents" after editing ⎕IO.apla

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#396]
When a Linked `⎕IO.apla` file is edited with an external editor and the value changed then in the APL session this is printed:

> Link Warning: ⎕SE.Link.Notify: changed D:/Temp/Kai/APLSource/⎕IO.apla: invalid file contents"

```
Dyalog  18.2.44386 64-bit Unicode, BuildID e8e930ba            
 OS      Windows 10 or Windows Server 2016 (10.0.19043) 64-bit  
 Link    3.0.8                                                  
 SALT    2.808                                                  
 UCMD    2.51                                                   
 .NET    .NET Framework 4.8.4420.0                              
 WS      18.2                                                   
````
Regarding Link I am on the bleeding edge.

(my <01939>)

**Comment by mkromberg** [comment]
I am unable to reproduce this, I have changed by ⎕IO.apla file several times, including deleting the trailing newline, and it works fine. Can you send me a copy of the ⎕IO.apla file that caused the problem?

Also: The error message is only issued in one place, line [89] of ⎕SE.Link.Notify, if you want to try and trace the problem yourself to see how it ends up here.

**Comment by aplteam** [comment]
Cannot reproduce it anymore either.
