### ISSUE TITLE
]link.CaseCode /path/to/file throws DOMAIN ERROR

### ISSUE THREAD

**Issue by e9gille** [Dyalog/link#40]
Looks like the command is expecting a simple string but is called with a nested array.

Also, if bypassing the issue, it seems the resulting name has an extra `/` injected for no good reason.

**Comment by abrudz** [comment]
`]Link.CaseCode` [has been withdrawn](https://github.com/Dyalog/link/commit/df50d4f8710cd4a395332446da3ffb222e893839#diff-5de32a01cb0d14695a2f73ce30c0bc87R15).
