### ISSUE TITLE
The new documentation site should be clearer about .NET

### ISSUE THREAD

**Issue by abrudz** [Dyalog/link#401]
1. It should mention up front that full functionality requires .NET
2. It should point at [where to get .NET](https://dotnet.microsoft.com/download) (and which versions are supported).

**Comment by rikedyp** [comment]
is it true (to the point of being worth mention in the documentation) that while:

- .NET Framework 4.0+
- .NET Core 3.1

are officially supported, other .NET versions *might* work but have not been tested?

**Comment by rikedyp** [comment]
Thought I'd (at least partially) addressed this. Weird that 0fcc8a1cf3443745b9e8dff9d414245bf358e596 didn't cross-reference properly

**Comment by rikedyp** [comment]
@abrudz Please close this if the above, ad05e6143f7c498ae58791086b0e5b21197a1a67 and cdc301b71d60cab3afb58f6c86d7c1c98f7a38e7 cover this.

These add the note found at the top of https://dyalog.github.io/link/3.0/Usage/Installation/ as well as the same note under https://dyalog.github.io/link/3.0/#link-fundamentals and https://dyalog.github.io/link/3.0/Usage/#saving-your-work
