### ISSUE TITLE
Multiple failures Under Classic when using non-default ⎕AVU

### ISSUE THREAD

**Issue by dyavc** [Dyalog/link#406]
**Describe the bug**
Link.Create generates 2 import errors on a directory if -watch is both but not if -watch is ns

**To Reproduce**
Steps to reproduce the behaviour:
obtain Win.zip from Dyalog Support and put it into c:\tmp\

]Link.Create #.Win c:\tmp\Win -casecode -source=dir -watch=both
Linked: #.Win ←→ c:\tmp\Win      
ERRORS ENCOUNTERED:              
2 import(s) failed:              
c:\tmp\Win\Init-1.aplf           
c:\tmp\Win\Reg-1\GetValue-11.aplf

**Expected behaviour**
Expect it to work like it does if you do :
]Link.Create #.Win c:\tmp\Win -casecode -source=dir -watch=ns

**Desktop (please complete the following information):**
Dyalog  18.2.44785 32-bit Classic, BuildID 669f22ef            
 OS      Windows 10 or Windows Server 2016 (10.0.19043) 32-bit  
 Link    3.0.8                                                  
 SALT    2.9                                                    
 UCMD    2.51                                                   
 .NET    .NET Framework 4.8.4420.0                              
 WS      18.2

**Comment by dyavc** [comment]
Also reproduces in this setup:
]Version
Dyalog  18.0.44437 32-bit Classic, BuildID b3684d37                  
 OS      Windows 8 or Windows Server 2012 or newer (6.2.9200) 32-bit  
 SALT    2.808, Link: 3.0.8                                           
 UCMD    2.4                                                          
 .NET    .NET Framework 4.8.4420.0                                    
 WS      18.0

**Comment by mkromberg** [comment]
The failure is reported by Link.Create, but the cause is that the source files were incorrectly translated by Link.Export.
