### ISSUE TITLE
]link.break mentions ]link.diff, but ]link.diff does not appear to be implemented.

### ISSUE THREAD

**Issue by RonM-Dyalog** [Dyalog/link#418]
**Describe the bug**
]link.break mentions ]link.diff, but ]link.diff does not appear to be implemented.

**To Reproduce**
      ]link.break
ERRORS ENCOUNTERED: Link.Resync is required to access other functions than Link.Status and Link.Diff
      ]link.Diff -?
No commands or groups match ]link.diff           

**Expected behaviour**
If this is just missing documentation as has been suggested, then documentation needs to be added for ]link.diff 

**Screenshots**

**Session transcript**
If applicable, copy your log in to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - APL version: [e.g. 18.0 Unicode 64-bit]
 - `⎕SE.Link.Version`: [e.g. 2.0.1]

**Additional context**

**Comment by mkromberg** [comment]
Messages and documentation updated in 3.0.10.
