### ISSUE TITLE
Exportable system variables should include ⎕LX

### ISSUE THREAD

**Issue by RonM-Dyalog** [Dyalog/link#419]
**Is your feature request related to a problem? Please describe.**
When using ]link to record the development state of a workspace, it would be very useful to keep the value of #.⎕LX as .apla file.

Without that, importing into a workspace from a directory tree will require an additional step of setting the ⎕LX value appropriately. It would be useful for ]link.import to take care of that detail.

**Describe the solution you'd like**
Extend the set of system variables that can be linked to a file to include ⎕LX.

**Describe alternatives you've considered**

**Additional context**

**Comment by abrudz** [comment]
If we allow this, must/should we restrict importing to `#`, as no other location can own a `⎕LX`?

**Comment by RonM-Dyalog** [comment]
That’s a quite reasonable restriction – at least unless or until localizing ⎕LX in places other than # is allowed, and has some useful meaning.

**Comment by mkromberg** [comment]
I changed the description of this issue and added it to the 3.1 milestone: if we are going to consider supporting ⎕LX, we might as well include all the workspace and session-scope system variables.

**Comment by abrudz** [comment]
This would be the job of a project manager, dbuild, or similar. Won't fix.
