### ISSUE TITLE
Support -casecode

### ISSUE THREAD

**Issue by e9gille** [Dyalog/link#43]
It should create file structure with case code suffix, both on folders (namespaces) and files.

**Comment by dyavc** [comment]
]link.create with -casecode does not seem to work:
)ns test
  ]link.Create test d:\git\test2 -source=ns -casecode -forcefilenames

I )cs test and )ed blah, and blah in the directory does not have a casecode in the filename.

**Comment by dyavc** [comment]
have a customer request that the -casecode on ]link.create be fixed as the customer says "windows , and it is problematic, to put code to file, if this feature doesn´t work properly."

**Comment by nicolas-dyalog** [comment]
fixed in link v2.1
