### ISSUE TITLE
Link.Export generates a DOMAIN ERROR, if function contains a linefeed 

### ISSUE THREAD

**Issue by leppa0708** [Dyalog/link#441]
**Describe the bug**
Link.Export reports a DOMAIN Error , if the src source contains a linefeed

**To Reproduce**
code←'R←1',⎕UCS 10
⎕FX'R←AplFuncWithLineFeed' code ⍝ Funktion(en) wie üblich schreiben' code
xx←⎕SE.Link.Export'#.AplFuncWithLineFeed' 'c:\temp\dietmar' 
DOMAIN ERROR: Unable to normalise the file or directory name

**Expected behaviour**
LInk.Export should return the error as a normal return code 

**Screenshots**

**Session transcript**

**Desktop (please complete the following information):**
]Version
 Dyalog  18.0.44437 32-bit Classic, BuildID b3684d37                  
 OS      Windows 8 or Windows Server 2012 or newer (6.3.9600) 32-bit  
 SALT    2.808, Link: 3.0.10                                          
 UCMD    2.4                                                          
 .NET    .NET Framework 4.8.4430.0                                    
 WS      18.0                                                         

**Additional context**

**Comment by mkromberg** [comment]
I think there is an error in the instructions to reproduce the error, there is an unbalanced quote and the variable code is not used - please verify?

**Comment by mkromberg** [comment]
@leppa0708: I adjusted the expression to fix the function, as the original instructions were incomplete, please verify that the instructions are now correct.

**Comment by mkromberg** [comment]
New output is:

      ⎕SE.Link.Export # 'c:\tmp\link441'
Exported: # → c:\tmp\link441
ERRORS ENCOUNTERED: 1 export(s) failed:
#.AplFuncWithLineFeed (contains new lines)

**Comment by leppa0708** [comment]
Hi Morten,

I checked it, it works, thank you !!

Regards,
Dietmar


Freundliche Grüße

Dietmar Appel
Software Digital & Print Solutions | M52

DATEV eG
Standort: Sigmundstr. 172
Telefon: +49(911)319-51831
Mobil: +49(172)8221911
E-Mail: ***@***.***
Postanschrift: DATEV eG, 90329 Nürnberg


– Intern –

-----Ursprüngliche Nachricht-----
Von: Morten Kromberg ***@***.***>
Gesendet: Sonntag, 2. Januar 2022 11:16
An: Dyalog/link ***@***.***>
Cc: Appel, Dietmar ***@***.***>; Mention ***@***.***>
Betreff: Re: [Dyalog/link] Link.Export generates a DOMAIN ERROR, if function contains a linefeed (Issue #441)

@leppa0708: I adjusted the expression to fix the function, as the original instructions were incomplete, please verify that the instructions are now correct.

--
Reply to this email directly or view it on GitHub:
https://github.com/Dyalog/link/issues/441#issuecomment-1003692842
You are receiving this because you were mentioned.

Message ID: ***@***.***>
________________________________
 Datenschutz
Informationen zum Umgang mit Ihren personenbezogenen Daten bei DATEV finden Sie unter https://www.datev.de/dsgvo-information
________________________________

DATEV eG
90329 Nürnberg
Telefon +49 911 319-0

E-Mail: ***@***.***
Internet: https://www.datev.de
Sitz: 90429 Nürnberg, Paumgartnerstraße 6-14
Registergericht Nürnberg, GenReg Nr. 70

Vorstand
Dr. Robert Mayr (Vorsitzender)
Prof. Dr. Peter Krug (stellv. Vorsitzender)
Julia Bangerth
Prof. Dr. Christian Bär
Diana Windmeißer

Vorsitzender des Aufsichtsrates: Nicolas Hofmann
