### ISSUE TITLE
References to external namespaces should be ignored

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#442]
When a reference in injected into a Linked namespace then it should be ignored.

Example:

```
      'Boo'⎕ns''
      )cs #.Boo
#.Boo
      'Foo'⎕ns''
      Foo.⎕fx'r←Hello' 'r←''Galaxy'''
      Goo←Foo
      ]Link.Create #.Boo C:\Boo
Linked: #.Boo ←→ C:\Boo[directory was created] 
```
This results in this directory structure:

```
\Foo           
  \Foo\Hello.aplf
\Goo           
  \Goo\Hello.aplf
\Hello.aplf    
```
That is already questionable. I think that `Goo` should instead be ignored because it is a ref.

But we can make it worse: edit `#.Boo.Goo.Hello` and replace "Galaxy" by "Universe".

In the WS everything is okay: both `Foo.Hello` and `Goo.Hello` return correctly "Universe. On disk `Foo/Hello.aplf` reads "Universe", but `Goo/Hello.aplf` reads "Galaxy", and that is plain wrong.

`]Link.ReSync` has also problems with that: 

```
]link.Resync
2 updates required: use -proceed option to synchronise                             
                                                                                   
 Name             Direction  File                   Comments                       
 #.Boo.Goo.Hello  →                                 Item has no corresponding file 
                  ←          C:/Boo/Goo/Hello.aplf  File has no corresponding item 
```

One more thing: when I load a Tatin package into the WS then the real thing goes into `#._tatin`. In `#.Boo` only a reference is injected:

```
      ]tatIN.LoadPackage [tatin]APLTreeUtils2 #.Boo
...
      APLTreeUtils2
#._tatin.aplteam_APLTreeUtils2_1_1_3.code.APLTreeUtils2
      ]Link.Resync
3 updates required: use -proceed option to synchronise                                 
                                                                                       
 Name                 Direction  File                   Comments                       
 #.Boo.APLTreeUtils2  →                                 Item has no corresponding file 
 #.Boo.Goo.Hello      →                                 Item has no corresponding file 
                      ←          C:/Boo/Goo/Hello.aplf  File has no corresponding item 
```

If the Tatin package would have been loaded into Boo before calling `]Link.Create` then it would have saved the APLTreeUtils2 class script, which is certainly not what the user wants.

I am on the bleeding edge: 3.0.13. This is my <01957>

**Comment by mkromberg** [comment]
The documentation states that Link only works with namespaces which have a display form corresponding to the name of the reference. However, the code does not currently ignore references which do not conform to this - and it should. In the example above, #.Boo.APLTreeUtils2 has a display form of '#._tatin.aplteam_APLTreeUtils2_1_1_3.code.APLTreeUtils2' and should be ignored.
