### ISSUE TITLE
documentation does not fold properly with okular, vi...

### ISSUE THREAD

**Issue by bernecky** [Dyalog/link#448]
The various *.md files do not appear to fold lines properly.

Commit #: bdf315f18b295bcef1969be9315dc88f6f52d4a4

Formatting the text to fit in narrower windows would help, as would
doing whatever .md files are supposed to do there. 

As an example: docs/Usage/Installation.md

Even better would be to make the installation automagic with the installation
of the APL interpreter.

**Comment by rikedyp** [comment]
The markdown files are plain text, so I'm not sure what is meant by "fold lines properly".
The documentation is rendered as a website at [https://dyalog.github.io/link](https://dyalog.github.io/link).
Link 3.0 will be included with Dyalog version 18.2

**Comment by bernecky** [comment]
Well, if it's just plain text, why name it xxx.md? The authors of most text-based docs are courteous enough
to keep their line widths to, say, 80 characters or less, so that people reading them with any editor or presenter-thingy can do so without having to scroll to read the stuff that is hidden in the great beyond.

Thanks.

**Comment by abrudz** [comment]
What @rikedyp meant is that the [markdown](https://en.wikipedia.org/wiki/Markdown) files are using a human-readable format, much like HTML and indeed APL source files. This is in contrast to things like word documents and workspaces which are binary blobs that are not readable in a plain text editor. Even so, the file extensions is intended to indicate proper usage, hence .md for MarkDown and .aplf for APL Functions etc. Regarding the 80-character limit. Most text editors are now able to wrap long lines, so there's no reason to force a specific width.
