### ISSUE TITLE
Using Link together with "shared code files" have negative effect on performance. (Dyalog reference 16653)

### ISSUE THREAD

**Issue by cenghoff** [Dyalog/link#47]
We often use a setup, where a large number of APL functions are stored in a shared code file.
All functions are in root namespace

When we link to files with "flatten"  option is takes a very long time compared to when all functions are in stored directly in the work space.

Two workarounds can be used short term:
1.	Call Assimilate Shared Code Files (8666⌶⎕NULL) before calling ]link
2.	Use ⎕EX to delete the functions etc. before calling ]link

**Comment by mkromberg** [comment]
Closed in version 3.0.2
