### ISSUE TITLE
]LINK -? hyperlink both broken and wrong

### ISSUE THREAD

**Issue by bpbecker** [Dyalog/link#473]
```
      ]link -?
````
Produces text that begins with
```
LINK          User commands for namespace-directory synchronisation (see https://github.com/dyalog/link/wiki):
  Add          Associate item in linked namespace with new file/directory in corresponding directory
```
The current hyperlink points to the Link 2.0 documentation and should instead be: https://dyalog.github.io/link/3.0/

Also, because of the way the interpreter tries to detect hyperlinks, the "):" is included in the hyperlink and results in a 404 error.

The simple solution is to change the text by adding surrounding spaces: ( see https://dyalog.github.io/link/3.0/ );

**Comment by abrudz** [comment]
Fixed (as part of SALT)
