### ISSUE TITLE
-quiet switch for ]link.import

### ISSUE THREAD

**Issue by dyavc** [Dyalog/link#509]
A Dyalog customer from Finland writes: It would be nice to have a “-quiet” option for ]link.import and ⎕SE.Link.Import (and actually all other commands where it makes sense), that would suppress output by the command. This is a standard option in many unix commands. I have some code which imports library code via ⎕SE.Link.Import when the workspace is started and these outputs just take up space on the screen unnecessarily.

**Comment by abrudz** [comment]
The user commands can be made quiet by inserting `←` between `]` and the command name, e.g. `]←import`

The API functions can be made quiet by prepending `{}` e.g. `{}⎕SE.Link.Import`

**Comment by dyavc** [comment]
The customer writes:  I see. I guess I withdraw my feature request then. :) Thanks!
