### ISSUE TITLE
"Run with Dyalog" on MS Windows on a folder generates an error 777

### ISSUE THREAD

**Issue by dyavc** [Dyalog/link#511]
**Describe the bug**
"Run with Dyalog" on MS Windows on a folder generates an error 777

**To Reproduce**
unzip the attached dummy.zip to a directory of your choice.  (e.g. D:\tmp\).   It creates a dummy folder.

Go into that dummy folder in Windows Explorer

Right click in empty space and choose "Run with Dyalog"

Linked: # ←→ D:\tmp\dummy
ERROR 777

**Expected behaviour**
The error 777 not to happen and the code in Run.aplf to be run.

**Desktop (please complete the following information):**
reproduced with Dyalog APL/W-64 Version 18.2.46656
OS Windows 10 or Windows Server 2016 (10.0.19045) 64-bit
 Link 3.0.19
 SALT 2.9
 UCMD 2.51
 .NET .NET Framework 4.8.4614.0

**Additional context**
If you choose "Load with Dyalog", it loads OK.

Additonal:  I think if you right click on the Run.aplf file and ask that to "Run with Dyalog", it seems to work OK.

This was originally logged in Mantis as 19898.

**Comment by dyavc** [comment]
[dummy.zip](https://github.com/Dyalog/link/files/10851808/dummy.zip)

here is the dummy.zip file

**Comment by mkromberg** [comment]
This error is directly caused by a the issue logged as Mantis #19739,. It happens with session files shipped with very early versions of 18.2. The solution is to use a recent version of the BUILDSE workspace and the BUILD_SESSION function to create a new session file.
