### ISSUE TITLE
All 'acknowledged' Dyalog APL fileextensions should be recognized by GitHub

### ISSUE THREAD

**Issue by stampes** [Dyalog/link#52]
Dyalog have elected a set of file extensions for their objects - these must be recognized by GitHub (and GitHub enterprise) - otherwise can the syntax highlighting not be used.

**Comment by abrudz** [comment]
I looked into this, and it may turn out to be a problem. [They write](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language) that (my emphasis):

> We try only to add new extensions once they have some usage on GitHub. In most cases we prefer that extensions be in use in ***hundreds of repositories*** before supporting them (...)

Maybe this is an argument for abandoning the nameclass-specific extensions?

**Comment by abrudz** [comment]
@stampes Would it be acceptable to add a **.gitattributes** file to each repository?

If so, add such a file to the root of relevant repositories, containing:
```
*.apl? linguist-language=APL
```
I've added [this file](https://github.com/Dyalog/link/blob/master/.gitattributes) to this repository, and GitHub now seems to colour **.aplf** files appropriately. See e.g. [this one](https://github.com/Dyalog/link/blob/master/StartupSession/Link/CaseCode.aplf).

**Comment by stampes** [comment]
We will look at that! Thanks

**Comment by skovsende** [comment]
You really ought to go to the Lingust guys and add aplf as an extension for apl files, may I suggest looking at this guide: https://github.com/github/linguist/blob/master/CONTRIBUTING.md

**Comment by cenghoff** [comment]
We have a lot of repositories with APL code in an Enterprise GitHub installation and prefer not to include **.gitattibutes** in all these.

**Comment by mkromberg** [comment]
We are reaching out to "the Linguist guys" to understand whether they will waive the stated requirement of "hundreds of repositories" as they clearly did for apl and dyalog, and accept a set of new extensions - at least aplf to begin with (but we also need apla aplo apln aplc and apli, if we are to support the full set according to the current design).

We are also investigating whether a Git Enterprise installation can have a custom default .gitattributes file, as a temporary work-around.

**Comment by abrudz** [comment]
@mkromberg Why not ask for `*.apl?` so we don't have to bother them again with any future extensions. We can even justify it by saying that `*.apl?` is like the existing `*.apl` but with a specification of the content.

**Comment by cenghoff** [comment]
@mkromberg I don't think you can set this "system wide". At least I found this issue: https://github.com/github/linguist/issues/4283

**Comment by e9gille** [comment]
> Why not ask for *.apl?

Can you use patterns?

**Comment by abrudz** [comment]
@e9gille See https://github.com/Dyalog/link/issues/52#issuecomment-488028638

**Comment by e9gille** [comment]
> @e9gille See [#52 (comment)](https://github.com/Dyalog/link/issues/52#issuecomment-488028638)

Sure, it just isn't obvious to me that patterns are allowed/supported in the https://github.com/github/linguist/blob/master/lib/linguist/languages.yml file.

**Comment by abrudz** [comment]
@e9gille [Turns out](https://stackoverflow.com/a/55938956/5306507):

> No, it doesn't.
> 
> We (I'm a co-maintainer of github-linguist) don't receive that many requests to add new extensions that we have felt a need to add this for now.
>
>[pchaigno](https://stackoverflow.com/users/6884590/pchaigno)

**Comment by mkromberg** [comment]
I think we have done as much as we can at this point; Dyalog will send a broadcast out to the user community to raise awareness and accelerate use of the new extensions and ultimately adoption by GitHub.

**Comment by nicolas-dyalog** [comment]
Closing the discussion. Not a Link issue.

**Comment by stampes** [comment]
Might not be a Link issue - but I do see this as a Dyalog issue...
