### ISSUE TITLE
Combine typeExtensions and codeExtensions and customExtensions

### ISSUE THREAD

**Issue by abrudz** [Dyalog/link#53]
It is confusing to have all these specifications. A single 2-column matrix based on the current `typeExtensions` is enough. All extensions listed in the right column will be considered as code extensions, and additional custom extensions (which still require custom handlers `beforeRead` and `beforeWrite`) can be listed with ¯1 as their type, while 0 indicates "everything else".

Link will scan down the first column to find a compatible entry. E.g. for tradfns (`3.1=⎕NC`), Link will use the first found of 0 (everything else) 3 (functions) 3.1 (tradfns).

The default `extensions` will be:

| Type | extension |
| ---- | --------- |
| 2    | apla      |
| 3    | aplf      |
| 4    | aplo      |
| 9.1  | apln      |
| 9.4  | aplc      |
| 9.5  | apli      |
| 0   | dyalog |

**Comment by mkromberg** [comment]
In my opinion, the current separation is useful because it allows a developer who wants to support new object types with custom extensions to only make changes to customExtensions. The other two settings should reflect defaults that users should ideally leave unchanged.
