### ISSUE TITLE
master README.md needs updating

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/link#533]
[2023-05-17] 
What will be released with 19.0 is the 3.1 branch.  This needs all the current commits in master to be merged into 3.1.
The README.md needs to be/will need to be updated to reflect this, and to mention Version 3.1.  Also, Version 3.0 section says "Until version 4.0" .. that should I think be "version 3.1"

**Comment by mkromberg** [comment]
The README for version 4.0 has been revised. Version 3.1 will soon be deleted.
