### ISSUE TITLE
If link/StartupSession/Link/GhostRider is not needed, please remove from 3.1 and master

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/link#538]
Cuirrently (2023-05-30) non-Windows installation images include link/StartupSession/Link/GhostRider which is an empty directory.

If it's not needed then we should remove it here.  Otherwise I can suppress in the installation images.

**Comment by mkromberg** [comment]
GhostRider is used by the QA, which we intend to remove from distribution with Link 4.0.

**Comment by mkromberg** [comment]
In Link 4.0, the test code has moved up and sideways to a separate folder "Test", which will not be included in the installation. A single function ⎕SE.Link.RunTests ' will imports the Test folder to #.Test and run the tests.

**Comment by mkromberg** [comment]
Fixed by commit bc1b7b080bbb2d4fb117b3bbc2372bcb61879e07
