### ISSUE TITLE
Gracefully handle empty files

### ISSUE THREAD

**Issue by abrudz** [Dyalog/link#566]
When creating a new file, some editors immediately write an empty file to disk, causing Link to complain about "invalid contents". We should ignore empty files, but possibly warn about them.

**Comment by mkromberg** [comment]
No output is produced by 4.0.11 if you

]link.create linkdemo c:\tmp\linkdemo
'c:\tmp\linkdemo\empty.aplf' ⎕NCREATE 0

**Comment by mkromberg** [comment]
Commit 4709f25
