### ISSUE TITLE
]link-export -?  crashes

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/link#567]
**Describe the bug**
the command crashes as shown in the repro

**To Reproduce**
Steps to reproduce the behaviour:
execute `]link.export -?`

**Expected behaviour**
Show help for this command.

**Session transcript**
```
⎕se.Link.Version
4.0.8
      ]link.export -?
* Unable to produce Help for command Export:INDEX ERROR
      ]UDEBUG ON
Was OFF
      ]link.export -?
INDEX ERROR
UCMD_Help[28] myModS←∊myMods{' [',⍺,⍵,']'}¨myModI⌷modVals
                                                 ∧
      myModI
┌────────────┐
│15 3 19 6 22│
└────────────┘
      ≢modVals
21
      myMods
┌──────────┬───────┬────────┬─────────┬─────────────┐
│-overwrite│-arrays│-sysvars│-casecode│-ignoreconfig│
└──────────┴───────┴────────┴─────────┴─────────────┘
```
**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - APL version: [e.g. 18.0 Unicode 64-bit]
 - `⎕SE.Link.Version`: [e.g. 2.0.1]

**Additional context**

**Comment by abrudz** [comment]
This should be fixed now.
