### ISSUE TITLE
Refresh calls "DefaultOpts" without providing an argument

### ISSUE THREAD

**Issue by abrudz** [Dyalog/link#57]
https://github.com/Dyalog/link/blob/bfdf024654f6095e2bd8b1a3b7902b968e66d4d4/StartupSession/Link/Refresh.aplf#L13

**Comment by lstefano71** [comment]
Yes! I noticed this during Morten's demo in Milano and thought I'd mention the fact but then forgot about it. I'm surprised he hasn't noticed himself :)


--
Stefano Lanzavecchia

________________________________
