### ISSUE TITLE
Mysterious SYNTAX ERROR tracing Link.Create

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/link#608]
AB/MB hit a SYNTAX ERROR when tracing through `#.o ⎕SE.Link.Create ⎕SE.CITA'/NASBuild/jenkins/nodes/p9-72qa/workspace/CITA_TestRepo_Label/CITA/StartupSession/CITA’` on statement in [11] `→(nohold←(''⍴1↓⎕XSI)∊⊂'⎕SE.Link.OnAfterFix')⍴NOHOLD`

_AB asked me to register this issue and so I copied the statement - but forgot the record tha value of `o` - and I wasn't able to repro the error, so I probably forgot half of the story already :(   I'm recording it anyway - maybe it'll help AB to remember what was going on. 
IIRC, we had done `(⍳999)⎕TRACE ⊃⎕SI` and the tracing may have affected the evaluation - but that's speculation already...._
 

**Desktop (please complete the following information):**
 - OS: AIX
 - 190u64.48240
 - `⎕SE.Link.Version`: 4.0.11

**Comment by abrudz** [comment]
I'm closing this since we cannot address it at the moment. Re-open if/when hit again.
