### ISSUE TITLE
Better Create failure msgs

### ISSUE THREAD

**Issue by abrudz** [Dyalog/link#615]
The error message "Destination directory not empty" from Create should be something like "Destination directory neither empty nor matching namespace"

**Comment by aplteam** [comment]
I find the proposed error message confusing, but maybe that's just me.

**Comment by abrudz** [comment]
@aplteam The issue is that "Destination directory not empty" is misleading when trying to re-establish the connection between a namespace and a directory, but differences have crept in. (If everything matches, Link will happily establish a connection, though both sides have contents.) Do you have a suggestion for a better general message? (Link cannot distinguish between the case where you're trying to link to an already used directory, and the case where there's a discrepancy in an otherwise sync'ed ns–dir pair.)

**Comment by aplteam** [comment]
Destination directory is not empty and does not match the specified namespace.
