### ISSUE TITLE
Strange warning when renaming a function in the editor

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/link#620]
When a function is renamed in the editor, the following warning appears:

Link/OnFix: Failed to get source of fixed item (VALUE ERROR: Undefined name: LookupRef)

Version tested: 4.0.13

**Comment by dyaandys** [comment]
I got it when I hit EP in the editor having renamed my function.  The error msg was
fooLink/OnFix: Failed to get source of fixed item (VALUE ERROR: Undefined name: LookupRef)

note: no space between "foo" and "Link".
