### ISSUE TITLE
How does Link deal with ⎕IO, ⎕ML, ⎕WX etc.?

### ISSUE THREAD

**Issue by abrudz** [Dyalog/link#63]
Maybe `Add` should allow system variables and simply make `⎕IO.apla` etc.

Currently, `Add` complains that `⎕IO`'s `⎕NC` is `¯1`

**Comment by ndrogers** [comment]
This would be nice to have more now than not.

**Comment by mkromberg** [comment]
If you need an urgent solution, there is a work-around for this, which is to create a scripted namespace with a name line _setup_, as follows:

:Namespace _setup_
      ##.⎕IO←1
      ##.⎕ML←1
      ⍝ etc
:EndNamespace

**Comment by aplteam** [comment]
I don't need a solution at all. In fact I wanted to make sure that Link does not - and will never - care about this kind of stuff because it is not a project manager.

**Comment by mkromberg** [comment]
@aplteam I agree Link is not a project management tool. However, I am not sure I can see how using a text file to define ⎕IO (or any other system variable) in a namespace classifies as "project management". Can you explain a bit more about your point of view?

**Comment by aplteam** [comment]
It doesn't. But then it's not done by Link, it's done by the user.

**Comment by abrudz** [comment]
I think Link should obey files called `⎕IO.apla` etc. and optionally create them with a new option `sysVars←1`. Acre can of course choose to ignore this ability, but simple usage of Link should have it as a possibility. Otherwise, we'll force people to use Acre or localise in every single item.

**Comment by mkromberg** [comment]
I would prefer for them to be treated the same way as all other variables: You need to Link.Add them. A sysVars setting raises the issue of *which* ones to save and does move us in the direction of project management. I would personally never want to save ALL system variables in every namespace.

**Comment by abrudz** [comment]
@mkromberg Good point. Currently one would have to notify Link manually of a change to `⎕IO` which is a bit awkward, but shouldn't happen often. Eventually, with full support for array notation, the editor should be able to edit `⎕IO` and thus save the change back.

**Comment by abrudz** [comment]
@ndrogers Link now supports both the Acre, using a namespace like @mkromberg suggested (but named `quadVars.apln`) and having files called `⎕IO.apla` etc. However, this is only for reading in from the directory. You must create these files manually.

**Comment by JoshDavid** [comment]
The most recent build of 17.1 does not include this feature. Running 17.1 built on Jul 3rd, ]link does not properly assign ⎕IO,etc. You can reproduce it with this acre repository https://github.com/JoshDavid/CEF-Utility . I know the code is out there to do it because I remember the fix being made. Maybe it just hasn't been pushed in the new build?
