### ISSUE TITLE
]link.status does not show the link if you ⎕CY a workspace saved with active links 

### ISSUE THREAD

**Issue by dyavc** [Dyalog/link#685]
**Describe the bug**
]link.status does not show the link if you ⎕CY a workspace saved with active links.
However, there is still a connection between the workspace and the files because if you )ed a function and fix it, the file gets changed.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
Expect ]link.status and ]link.break -all to work as if you had )load'd the workspace.

**Session transcript**
)clear
clear ws
      ]link.create # d:\temp\linktest5
Linked: # ←→ d:\temp\linktest5
      0 ⎕save 'd:\tmp\myworkspace.dws'
      )off

⍝ Now start a new Dyalog
⎕cy 'd:\tmp\myworkspace.dws'
      ]link.status
No active links
      )fns
RUN2    foo     
      )ed foo
⍝ any changes I make to foo are reflected in the directory even though ]link.status said there aren't any links.

**Desktop (please complete the following information):**
      ]tools.version
 Dyalog  19.0.50236 64-bit Unicode, BuildID 38f63899            
 OS      Windows 10 or Windows Server 2016 (10.0.19045) 64-bit  
 Link    4.0.17                                                 
 SALT    2.915                                                  
 UCMD    2.6                                                    
 .NET    .NET Framework 4.8.9282.0                              
 WS      19.0                                                   
 Tatin   0.112.1                                                
 Cider   0.42.2

**Comment by dyavc** [comment]
[linktest5.zip](https://github.com/user-attachments/files/18041194/linktest5.zip)
Attached please find a zip file containing my linktest5 directory if you need it.

**Comment by mkromberg** [comment]
Link is designed to support the use of text files as source. It is not designed to work in a mixed mode where some of your source is in workspaces, and some in text files. You can )SAVE a workspace with links and reload it if you need to end and resume a session, but I cannot see us supporting )COPY from workspaces containing links any time soon. 

I have logged #686 as a documentation issue to warn about this problem, but am closing this issue now: this is simply not a supported mode of operation.
