### ISSUE TITLE
Error when linking # in non-empty ws with empty target dir

### ISSUE THREAD

**Issue by e9gille** [Dyalog/link#7]
We discussed this, I know. I think we said "error if both ns and dir non-empty"

1. When first "exporting" dws content to file, target dir would be empty and there is no risk.

2. When loading into `#` from disk, we only need to signal error if `#` not empty.

**Comment by e9gille** [comment]
> I'm not sure whether this is a complain about existing functionality? I think the behavior is as you want it?

It is not a complaint, I'm just reporting on things I come across when testing it. That way we can discuss and agree on a way forward.

Well, I tested scenario 1 and got the error that I need to specify source, even if the target dir is empty. In that case there is no doubt what the source is and it should therefore be safe to assume the ns is the source. Don't you think?

**Comment by mkromberg** [comment]
The test now applies to all spaces and is
"-source must be specified when linking a non-empty namespace to a non-empty folder"
