### ISSUE TITLE
Make Import and Export handle single items

### ISSUE THREAD

**Issue by abrudz** [Dyalog/link#79]
i.e. not just unscripted nss

**Comment by abrudz** [comment]
Import already works. But I don't see how Export can work syntactically.

`]Export mything /mydir` will attempt to export everything *in* `mything`, not the item itself.

**Comment by nicolas-dyalog** [comment]
The undocumented behaviour of import was reverted in v2.1 where import only accepts directories.
We need to make a global design decision on how to handle individual files, and not let people use them until then.

**Comment by nicolas-dyalog** [comment]
Fixed in link v2.1.0-beta7
