### ISSUE TITLE
)CLEAR keeps links active

### ISSUE THREAD

**Issue by e9gille** [Dyalog/link#8]
I `)CLEAR`ed and then attempted re-running the link cmd only to find that it was still active.

Expected to see an automatic reset of all links. Is that reasonable?

**Comment by mkromberg** [comment]
Would it be OK if we put some kind of _link_obj instance with a destructor in the top-level linked namespace? I can't think of any other way to capture the destruction of a linked space.

**Comment by mkromberg** [comment]
Fixed in distributions containing Dyalog v17.0.32677 or later.
