### ISSUE TITLE
Case-coding hex vs octal

### ISSUE THREAD

**Issue by PaulMansour** [Dyalog/link#93]
Link is octal. Acre is currently hex.  I think the only reason Link supports case-codes is be compatible with Acre. Did the Acre team agree to change to octal? I can't remember. 

Does the Link team have any objection to changing to hex?

Aside from whatever is decided, is the trade off simply one of having only digits in the octal, which presumably is more pleasing to the eye, at the expense of a slightly longer code in some cases?  

Is there any specific problem with having alpha chars in the case code?

**Comment by lstefano71** [comment]
I am using the same convention as Link to call the file names produced by my internal tool. If I moved from octal to hex several thousand files in a couple of repos would change their name. If Git is smart enough, it would flag them as several thousand renames. If not, several thousands deletes, followed by several thousand additions and the history of the files (really, APL objects) would be lost. I could give it a go. Has anybody already tried and can report on the result?

**Comment by PaulMansour** [comment]
I vaguely remember doing something like this a while ago, when we renamed all our extensions. If I remember correctly, I was surprised that Git renamed everything and history was not lost. However, its been a while, and I wouldn't bank on it without trying it again in an experimental test run myself.

**Comment by abrudz** [comment]
Yes, the Acre team agreed to move to octal because the whole reason for CaseCoding is avoiding ambiguity and file name clashes, but hexadecimal introduces yet another layer of clash, e.g. `GETDATA-7f.aplf` vs `GETDATA-7F.aplf`.

**Comment by PaulMansour** [comment]
Can you refresh my memory on why hex introduces another layer of clash? Everything after the dash, like everything after the dot, is case insensitive; the case is not used for anything and doesn't matter. No?  Is there some problem that can arise from this? What about `GETDATA.aplf`  vs `GETDATA.aplF'? I'm sure I'm missing something, and apologies if we have hashed this out before.
