### ISSUE TITLE
with ]boxing -fns=on, ]link.create shows an empty box 

### ISSUE THREAD

**Issue by dyavc** [Dyalog/link#96]
Reproduced in DSS 2019-08-15 17.1.36847.0, 64-bit 17.1 Unicode_DV_64.exe  9ee5c1df   
<pre>

]boxing ON -style=max -trains=tree -fns=on

]link.create # c:/git/abcde/
┌⊖──────────────────────────────┐
│ ┌→──────────────────────────┐ │
│ │                           │ │
│ └───────────────────────────┘ │
└∊──────────────────────────────┘
┌→────────────────────────┐
│Linked: # ←→ c:\git\abcde│
└─────────────────────────┘
      ]uversion link.create
┌→────────────────────────────────────────────────────────────────────────────────────┐
↓framework:  2.4                                                                      │
│command:    ]LINK.Create                                                             │
│source:     C:\Program Files\Dyalog\Dyalog APL-64 17.1 Unicode\SALT\spice\Link.dyalog│
│version:    2.09                                                                     │
│revision:                                                                            │
│commit:     2019 06 19 Adam: Avoid special-cased vars in caller                      │
│                                                                                     │
└─────────────────────────────────────────────────────────────────────────────────────┘
</pre>

**Comment by abrudz** [comment]
This has been fixed in master

**Comment by dyavc** [comment]
Great, Thanks!
